/*
 * SEED_MANUAL — Bader's own captured vocabulary, curated.
 *
 * reg:  "kw"     = كويتي صرف (pure dialect)
 *       "msa"    = فصحى مستخدمة بالحچي الراقي (MSA used in elevated Kuwaiti speech)
 *       "phrase" = عبارة / تعبير جاهز
 *       "tip"    = ملاحظة استخدام (register upgrade)
 * Items flagged with a note beginning ⚠ were captured ambiguously in the
 * original list and carry the best reading plus what to confirm.
 */
const SEED_MANUAL = [
  { id: "m001", ar: "يتجاوز", tr: "yitjāwaz", en: "to exceed, go beyond", reg: "msa", topic: "نقاش", ex: "المصروف هالشهر تجاوز الميزانية اللي حاطينها." },
  { id: "m002", ar: "جودة", tr: "jōda", en: "quality", reg: "msa", topic: "شغل", ex: "الفرق واضح بين المطعمين — الجودة عندهم أهم من الكمية." },
  { id: "m003", ar: "ينطبق على", tr: "yinṭabiq ʿala", en: "applies to", reg: "msa", topic: "نقاش", ex: "القانون اليديد ما ينطبق على اللي سجلوا قبل ٢٠٢٠." },
  { id: "m004", ar: "على سبيل المثال", tr: "ʿala sabīl il-mithāl", en: "for example", reg: "phrase", topic: "نقاش", ex: "أكو حلول وايد — على سبيل المثال، نقدر نبدأ بالتدريب قبل التوظيف." },
  { id: "m005", ar: "شريحة من الناس", tr: "sharīḥa min in-nās", en: "a segment of people", reg: "phrase", topic: "مجتمع", ex: "هالقرار بيأثر على شريحة كبيرة من الناس، مو بس فئة وحدة." },
  { id: "m006", ar: "منتج / منتجة", tr: "muntij / muntija", en: "productive", reg: "msa", topic: "شغل", ex: "أبي أكون منتج أكثر بدوامي، مو بس مشغول." },
  { id: "m007", ar: "إصلاح", tr: "iṣlāḥ", en: "reform; repair", reg: "msa", topic: "سياسة", ex: "الإصلاح الاقتصادي يحتاج قرارات صعبة، مو بس تصريحات." },
  { id: "m008", ar: "إشكالية", tr: "ishkāliyya", en: "problematic issue", reg: "msa", topic: "نقاش", ex: "الإشكالية مو بالفكرة نفسها — الإشكالية بالتطبيق." },
  { id: "m009", ar: "افترض", tr: "iftaraḍ", en: "to assume, suppose", reg: "msa", topic: "نقاش", ex: "لا نفترض إن كل شي بيمشي زين، خلنا نحط خطة بديلة." },
  { id: "m010", ar: "قطاع خاص", tr: "qiṭāʿ khāṣ", en: "private sector", reg: "msa", topic: "اقتصاد", ex: "وايد شباب الحين يفضلون القطاع الخاص عقب التخرج." },
  { id: "m011", ar: "قطاع حكومي", tr: "qiṭāʿ ḥukūmi", en: "public / government sector", reg: "msa", topic: "اقتصاد", ex: "الرواتب بالقطاع الحكومي ثابتة، بس التطور فيه أبطأ." },
  { id: "m012", ar: "مجتمع", tr: "mujtamaʿ", en: "society, community", reg: "msa", topic: "مجتمع", ex: "التغيير الحقيقي يبدأ من المجتمع نفسه، مو من فوق." },
  { id: "m013", ar: "وافد", tr: "wāfid", en: "expatriate resident", reg: "msa", topic: "مجتمع", ex: "نسبة الوافدين بالكويت أعلى بوايد من نسبة المواطنين." },
  { id: "m014", ar: "مواطن", tr: "muwāṭin", en: "citizen", reg: "msa", topic: "مجتمع", ex: "المواطن والوافد، كلهم يستفيدون إذا تحسنت الخدمات." },
  { id: "m015", ar: "المخرجات التعليمية", tr: "il-mukhrajāt it-taʿlīmiyya", en: "educational outcomes", reg: "msa", topic: "تعليم", ex: "المخرجات التعليمية عندنا ما تواكب متطلبات سوق العمل." },
  { id: "m016", ar: "يستخدم", tr: "yistakhdim", en: "to use, utilize", reg: "msa", topic: "يومي", ex: "أغلب الناس يستخدمون التطبيق يوميًا بس ما يعرفون نص مزاياه." },
  { id: "m017", ar: "كفاءة", tr: "kafāʾa", en: "efficiency, competence", reg: "msa", topic: "شغل", ex: "المشكلة مو بعدد الموظفين — المشكلة بالكفاءة.", note: "الإملاء الصحيح: كفاءة (مو كفائة)" },
  { id: "m018", ar: "شخّص", tr: "shakhkhaṣ", en: "to diagnose (a problem)", reg: "msa", topic: "نقاش", ex: "قبل لا نحكم على الحل، لازم نشخّص المشكلة صح." },
  { id: "m019", ar: "مجازي", tr: "majāzi", en: "figurative, metaphorical", reg: "msa", topic: "ثقافة", ex: "لا تاخذ كلامي حرفي — قصدي مجازي." },
  { id: "m020", ar: "واضح", tr: "wāḍiḥ", en: "clear, evident", reg: "msa", topic: "نقاش", ex: "خل نكون واضحين من البداية عشان ماكو سوء فهم عقب." },
  { id: "m021", ar: "محاورة", tr: "muḥāwara", en: "dialogue, structured debate", reg: "msa", topic: "نقاش", ex: "الفرق بين الجدال والمحاورة إنك تسمع قبل لا ترد." },
  { id: "m022", ar: "معيار", tr: "miʿyār", en: "standard, criterion", reg: "msa", topic: "نقاش", ex: "شنو المعيار اللي نقيس فيه النجاح؟ الفلوس بروحها مو كافية.", note: "⚠ مسجلة عندك «معيارz see» — الأغلب قصدك معيار/معايير" },
  { id: "m023", ar: "فنّش", tr: "fannash", en: "to lay off, fire (from work)", reg: "kw", topic: "شغل", ex: "الشركة فنّشت نص الموظفين بسبة الأزمة.", note: "كويتية أصيلة من الإنجليزية finish — «فنشوه» يعني أنهوا خدماته" },
  { id: "m024", ar: "استقلالية", tr: "istiqlāliyya", en: "independence, autonomy", reg: "msa", topic: "مجتمع", ex: "أهم شي بالتربية إنك تعطي اليهال شوية استقلالية." },
  { id: "m025", ar: "طموح", tr: "ṭumūḥ", en: "ambition", reg: "msa", topic: "شغل", ex: "الطموح زين، بس بدون خطة يظل حلم." },
  { id: "m026", ar: "اقتصاد", tr: "iqtiṣād", en: "economy", reg: "msa", topic: "اقتصاد", ex: "اقتصادنا كله مربوط بالنفط، وهني بالضبط المشكلة." },
  { id: "m027", ar: "مهارات", tr: "mahārāt", en: "skills", reg: "msa", topic: "تعليم", ex: "الشهادة تفتح لك الباب، بس المهارات هي اللي تخليك داخل." },
  { id: "m028", ar: "عشوائي", tr: "ʿashwāʾi", en: "random, haphazard", reg: "msa", topic: "نقاش", ex: "القرارات عندهم عشوائية — ماكو تخطيط واضح." },
  { id: "m029", ar: "نسبة", tr: "nisba", en: "percentage, ratio", reg: "msa", topic: "اقتصاد", ex: "نسبة النجاح ارتفعت، بس الأرقام ما تقول كل شي." },
  { id: "m030", ar: "تصوّر", tr: "taṣawwur", en: "conception, mental picture", reg: "msa", topic: "نقاش", ex: "عطني تصوّر عام عن المشروع قبل لا ندش بالتفاصيل." },
  { id: "m031", ar: "استمر / استمرينا", tr: "istamarr / istamarrēna", en: "to continue / we kept going", reg: "msa", topic: "شغل", ex: "تعبنا أول سنة بس استمرينا، والحين قاعدين نشوف النتيجة." },
  { id: "m032", ar: "ما زلنا", tr: "mā zilnā", en: "we still, we remain", reg: "msa", topic: "نقاش", ex: "ما زلنا في بداية الطريق — الشغل الصعب بعده ياي." },
  { id: "m033", ar: "عساك على القوة", tr: "ʿasāk ʿa l-guwwa", en: "may you stay strong (greeting to someone at work)", reg: "kw", topic: "مجاملات", ex: "تدخل على أحد قاعد يشتغل: «عساك على القوة!» — والرد: «الله يقويك».", note: "من أجمل التحايا الكويتية لأهل الشغل" },
  { id: "m034", ar: "سوّف / تسويف", tr: "sawwaf / taswīf", en: "to procrastinate / procrastination", reg: "msa", topic: "يومي", ex: "لا تسوّف — اللي تقدر تخلصه اليوم لا تأجله لباچر.", note: "⚠ مسجلة عندك «اسواف حق ___» — أقرب قراءة: أسوّف. أكّدها من السياق اللي سمعتها فيه" },
  { id: "m035", ar: "مكونات ثقافية", tr: "mukawwināt thaqāfiyya", en: "cultural components", reg: "msa", topic: "ثقافة", ex: "هويتنا الكويتية فيها مكونات ثقافية بحرية وبدوية وحضرية." },
  { id: "m036", ar: "يتضمن", tr: "yataḍamman", en: "to include, entail", reg: "msa", topic: "شغل", ex: "العرض يتضمن التدريب والدعم الفني، كله بسعر واحد." },
  { id: "m037", ar: "رداءة", tr: "radāʾa", en: "poor quality, shoddiness", reg: "msa", topic: "نقاش", ex: "رداءة التنفيذ خربت فكرة كانت ممتازة على الورق." },
  { id: "m038", ar: "سلوكيات", tr: "sulūkiyyāt", en: "behaviors", reg: "msa", topic: "مجتمع", ex: "التغيير الحقيقي يبدأ من سلوكيات صغيرة تتكرر كل يوم." },
  { id: "m039", ar: "منهج", tr: "manhaj", en: "curriculum; method", reg: "msa", topic: "تعليم", ex: "المنهج الدراسي محتاج تحديث يواكب العصر.", note: "⚠ مسجلة عندك «مناج» — الأغلب منهج (ومناخ موجودة ببطاقة ثانية)" },
  { id: "m040", ar: "أعتقد / نعتقد", tr: "aʿtaqid / naʿtaqid", en: "I believe / we believe", reg: "msa", topic: "نقاش", ex: "أعتقد الموضوع يحتاج وقت أكثر من اللي نتوقعه — وهذا طبيعي." },
  { id: "m041", ar: "أفقي", tr: "ufuqi", en: "horizontal; big-picture (talk)", reg: "msa", topic: "نقاش", ex: "قاعد أتكلم بشكل أفقي — يعني عن الصورة العامة، مو التفاصيل." },
  { id: "m042", ar: "ينظّم", tr: "yunaẓẓim", en: "to organize, regulate", reg: "msa", topic: "سياسة", ex: "القانون اليديد ينظّم العلاقة بين المؤجر والمستأجر." },
  { id: "m043", ar: "يتفوق", tr: "yitfawwaq", en: "to excel, outperform", reg: "msa", topic: "تعليم", ex: "ولدهم يتفوق على ربعه بكل شي، ما شاء الله عليه." },
  { id: "m044", ar: "استثنائي", tr: "istithnāʾi", en: "exceptional", reg: "msa", topic: "نقاش", ex: "الظروف استثنائية، فالقرارات بعد لازم تكون استثنائية." },
  { id: "m045", ar: "متحضر", tr: "mitḥaḍḍir", en: "civilized", reg: "msa", topic: "مجتمع", ex: "النقاش المتحضر ما يحتاج صوت عالي." },
  { id: "m046", ar: "قرارات", tr: "qarārāt", en: "decisions", reg: "msa", topic: "شغل", ex: "القرارات الصعبة اليوم أهون من الندم باچر." },
  { id: "m047", ar: "الواعي", tr: "il-wāʿi", en: "the aware, conscious (one)", reg: "msa", topic: "مجتمع", ex: "المستهلك الواعي يقارن ويسأل قبل لا يشتري." },
  { id: "m048", ar: "أعبّر", tr: "aʿabbir", en: "I express", reg: "msa", topic: "نقاش", ex: "أحيان أعرف شنو أحس، بس ما أعرف أعبّر عنه بكلمات." },
  { id: "m049", ar: "فجوة", tr: "fajwa", en: "gap", reg: "msa", topic: "تعليم", ex: "أكو فجوة كبيرة بين مخرجات التعليم ومتطلبات السوق." },
  { id: "m050", ar: "أوصف", tr: "awṣif", en: "I describe", reg: "msa", topic: "نقاش", ex: "خلني أوصف لك الوضع بمثال بسيط." },
  { id: "m051", ar: "ملمّ بـ", tr: "mulimm bi", en: "well-versed in", reg: "msa", topic: "شغل", ex: "نحتاج ناس ملمّين بالتقنية وبالسوق المحلي بنفس الوقت." },
  { id: "m052", ar: "ممتلئ", tr: "mumtaliʾ", en: "full, filled up", reg: "msa", topic: "يومي", ex: "جدولي ممتلئ هالأسبوع — خل نأجلها للأسبوع الياي." },
  { id: "m053", ar: "تعاطي", tr: "taʿāṭi", en: "handling / dealing with; (drug) use", reg: "msa", topic: "مجتمع", ex: "طريقة تعاطي الإعلام مع الموضوع زادت الطين بلة." },
  { id: "m054", ar: "مستقر", tr: "mustaqirr", en: "stable, settled", reg: "msa", topic: "اقتصاد", ex: "أبي وضع مالي مستقر قبل لا أفكر بمشروع يديد." },
  { id: "m055", ar: "تجسير", tr: "tajsīr", en: "bridging (a gap)", reg: "msa", topic: "تعليم", ex: "دورات التجسير تساعد على سد الفجوة بين التخصصات." },
  { id: "m056", ar: "تسيّب", tr: "tasayyub", en: "laxity, negligence", reg: "msa", topic: "شغل", ex: "التسيّب الإداري هو اللي موصّلنا لهالمرحلة." },
  { id: "m057", ar: "ممارسات", tr: "mumārasāt", en: "practices", reg: "msa", topic: "شغل", ex: "ناخذ أفضل الممارسات العالمية ونكيّفها على سوقنا.", note: "الإملاء: ممارسات (مسجلة عندك «ممارسلت»)" },
  { id: "m058", ar: "ممتاز", tr: "mumtāz", en: "excellent", reg: "msa", topic: "يومي", ex: "شغلك ممتاز — بس عندي ملاحظتين بسيطات." },
  { id: "m059", ar: "أنكر", tr: "ankar", en: "to deny", reg: "msa", topic: "نقاش", ex: "ما أقدر أنكر إن الفكرة نجحت أكثر من توقعي." },
  { id: "m060", ar: "أبذل مجهود", tr: "abdhil majhūd", en: "to put in effort", reg: "phrase", topic: "شغل", ex: "إذا ما تبذل مجهود حقيقي، لا تنتظر نتيجة مختلفة." },
  { id: "m061", ar: "مصطلحات", tr: "muṣṭalaḥāt", en: "terminology", reg: "msa", topic: "تعليم", ex: "كل مجال له مصطلحاته، وأول خطوة للاحتراف إنك تتقنها." },
  { id: "m062", ar: "قبل فترة", tr: "gabil fatra", en: "a while ago", reg: "phrase", topic: "يومي", ex: "قبل فترة قريت عن نفس الموضوع — خل أدور لك المقال." },
  { id: "m063", ar: "هامشية", tr: "hāmishiyya", en: "marginal, of little impact", reg: "msa", topic: "نقاش", ex: "هذي نقطة هامشية — لا نضيّع وقت النقاش عليها." },
  { id: "m064", ar: "نايس", tr: "nāys", en: "nice (casual borrowing)", reg: "kw", topic: "يومي", ex: "المكان نايس بس الأسعار شوي غالية.", note: "دارجة بين الشباب — للجلسات غير الرسمية، مو للنقاش الجاد" },
  { id: "m065", ar: "هيكل", tr: "haykal", en: "structure (organizational)", reg: "msa", topic: "شغل", ex: "قبل ما نوظف أحد، لازم نرتب الهيكل التنظيمي للشركة." },
  { id: "m066", ar: "من جد / من صج", tr: "min jidd / min ṣij", en: "seriously, for real", reg: "kw", topic: "يومي", ex: "من صج؟ ما توقعت هالخبر أبد!", note: "⚠ مسجلة عندك «جد جديد» — الأقرب «من جد». والأصيل الكويتي: «صج / من صج»" },
  { id: "m067", ar: "لبّى / لبّيت", tr: "labba / labbēt", en: "to answer a call or invitation", reg: "msa", topic: "مجاملات", ex: "عزموني على العشاء ولبّيت — ما يصير أردهم." },
  { id: "m068", ar: "عدة مواد", tr: "ʿiddat mawādd", en: "several subjects / clauses", reg: "msa", topic: "تعليم", ex: "الدورة تغطي عدة مواد، من المالية إلى التسويق." },
  { id: "m069", ar: "كادر", tr: "kādir", en: "cadre; pay scale for a profession", reg: "msa", topic: "شغل", ex: "أقروا كادر يديد للمهندسين برواتب أحسن." },
  { id: "m070", ar: "يعزز سلوك معين", tr: "yuʿazziz sulūk muʿayyan", en: "reinforces a certain behavior", reg: "phrase", topic: "تعليم", ex: "المكافأة الفورية تعزز السلوك اللي تبيه يتكرر." },
  { id: "m071", ar: "ما في إشكال", tr: "mā fī ishkāl", en: "no objection, no problem (formal)", reg: "phrase", topic: "مجاملات", ex: "إذا تبون نأجل الاجتماع، ما في إشكال عندي.", note: "بالكويتي الصرف: «ماكو إشكال»" },
  { id: "m072", ar: "خصوصية", tr: "khuṣūṣiyya", en: "privacy", reg: "msa", topic: "مجتمع", ex: "احترام الخصوصية أساس، حتى بين أقرب الأهل." },
  { id: "m073", ar: "إحساس بالملكية", tr: "iḥsās bil-milkiyya", en: "sense of ownership", reg: "phrase", topic: "شغل", ex: "إذا الموظف عنده إحساس بالملكية، يشتغل كأن المشروع ماله." },
  { id: "m074", ar: "النهضة", tr: "in-nahḍa", en: "renaissance, awakening", reg: "msa", topic: "ثقافة", ex: "نهضة أي دولة تبدأ من التعليم قبل العمران.", note: "معناها الدقيق: نهوض وازدهار (مو uprising بمعنى ثورة — الثورة شي ثاني)" },
  { id: "m075", ar: "احتكاك", tr: "iḥtikāk", en: "friction; exposure to people", reg: "msa", topic: "مجتمع", ex: "الاحتكاك بناس من خلفيات مختلفة يوسّع أفقك." },
  { id: "m076", ar: "بالمقابل", tr: "bil-muqābil", en: "in return; on the other hand", reg: "msa", topic: "نقاش", ex: "بالمقابل، لازم نعترف إن للقرار تكاليفه." },
  { id: "m077", ar: "استغلال", tr: "istighlāl", en: "exploitation; making use of", reg: "msa", topic: "نقاش", ex: "استغلال الوقت مهارة — والفرق بينه وبين الاستغلالية كبير." },
  { id: "m078", ar: "عقبات", tr: "ʿaqabāt", en: "obstacles", reg: "msa", topic: "شغل", ex: "أي مشروع بتطلع له عقبات — المهم شلون تتعامل وياها." },
  { id: "m079", ar: "نمط", tr: "namaṭ", en: "pattern, style", reg: "msa", topic: "نقاش", ex: "لاحظت نمط يتكرر عندنا: نتحمس، نبدأ، وما نكمل." },
  { id: "m080", ar: "أؤيد", tr: "uʾayyid", en: "I support, I second", reg: "msa", topic: "نقاش", ex: "أؤيد الاقتراح، بس بشرط نحدد ميزانية واضحة." },
  { id: "m081", ar: "العلاقات البيئية", tr: "il-ʿalāqāt il-bīʾiyya", en: "ecological relations", reg: "msa", topic: "عمران", ex: "التخطيط الزين يراعي العلاقات البيئية بالمنطقة قبل البناء." },
  { id: "m082", ar: "عازل", tr: "ʿāzil", en: "insulator, isolator", reg: "msa", topic: "علوم", ex: "حطوا عازل حراري فوق السطح — فرقت الفاتورة وايد." },
  { id: "m083", ar: "استوعبت", tr: "istawʿabt", en: "I grasped, absorbed (an idea)", reg: "msa", topic: "تعليم", ex: "أول مرة ما فهمت، بس عقب ما انعاد الشرح استوعبت." },
  { id: "m084", ar: "مقترحات", tr: "muqtaraḥāt", en: "proposals, suggestions", reg: "msa", topic: "شغل", ex: "حطوا مقترحاتكم بالجدول وبنناقشها وحدة وحدة." },
  { id: "m085", ar: "نباتات", tr: "nabātāt", en: "plants, vegetation", reg: "msa", topic: "علوم", ex: "زرعنا نباتات محلية تتحمل حرارة صيفنا." },
  { id: "m086", ar: "نسبيًا", tr: "nisbiyyan", en: "relatively", reg: "msa", topic: "نقاش", ex: "الأسعار نسبيًا معقولة إذا قارناها بالسنة اللي طافت.", note: "نسبيًا = relatively، أما «نسبة» فهي رقم محدد" },
  { id: "m087", ar: "التخطيط العمراني", tr: "it-takhṭīṭ il-ʿumrāni", en: "urban planning", reg: "msa", topic: "عمران", ex: "التخطيط العمراني عندنا يحتاج نظرة أبعد من عشر سنين." },
  { id: "m088", ar: "مثل ما تفضلت", tr: "mithil ma tfaḍḍalt", en: "as you kindly said", reg: "phrase", topic: "مجاملات", ex: "مثل ما تفضلت، الموضوع يحتاج دراسة أعمق.", note: "أرقى من «مثل ما قلت» — ترفع مستوى النقاش وتكرم محاورك" },
  { id: "m089", ar: "جذور", tr: "judhūr", en: "roots (lit. & fig.)", reg: "msa", topic: "ثقافة", ex: "المشكلة جذورها قديمة — ما طلعت فجأة." },
  { id: "m090", ar: "مسودة", tr: "musawwada", en: "draft", reg: "msa", topic: "شغل", ex: "جهزت مسودة أولية — عطني رأيك قبل لا نرسلها." },
  { id: "m091", ar: "إطار", tr: "iṭār", en: "frame, framework, lens", reg: "msa", topic: "نقاش", ex: "خل نتفق على إطار عام للنقاش قبل لا ندش بالتفاصيل.", note: "الإملاء: إطار (مو ايطار)" },
  { id: "m092", ar: "كفاءات", tr: "kafāʾāt", en: "qualified people, competencies", reg: "msa", topic: "شغل", ex: "الكويت فيها كفاءات، بس تحتاج بيئة تحتضنها." },
  { id: "m093", ar: "حافز", tr: "ḥāfiz", en: "incentive, motive", reg: "msa", topic: "شغل", ex: "بدون حوافز واضحة، لا تتوقع أداء استثنائي." },
  { id: "m094", ar: "استجواب", tr: "istijwāb", en: "interrogation; parliamentary grilling", reg: "msa", topic: "سياسة", ex: "الاستجواب أداة دستورية بمجلس الأمة، مو وسيلة ضغط شخصية." },
  { id: "m095", ar: "هدر المال", tr: "hadr il-māl", en: "waste of money", reg: "msa", topic: "اقتصاد", ex: "المشاريع المتعطلة سنين هي عين الهدر للمال العام." },
  { id: "m096", ar: "تكدس", tr: "takaddus", en: "piling up, overcrowding", reg: "msa", topic: "مجتمع", ex: "التكدس بالمستشفيات دليل خلل بالتوزيع، مو بس نقص أسرّة." },
  { id: "m097", ar: "علة", tr: "ʿilla", en: "deep flaw, root ailment", reg: "msa", topic: "نقاش", ex: "هذي مو مشكلة سطحية — هذي علة بالنظام نفسه." },
  { id: "m098", ar: "توزيع الثروة", tr: "tawzīʿ ith-tharwa", en: "wealth distribution", reg: "msa", topic: "اقتصاد", ex: "النقاش الحقيقي عن عدالة توزيع الثروة، مو عن حجمها." },
  { id: "m099", ar: "مقارنة", tr: "muqārana", en: "comparison", reg: "msa", topic: "نقاش", ex: "المقارنة العادلة تكون بين ظروف متشابهة." },
  { id: "m100", ar: "ثقافة استهلاكية", tr: "thaqāfa istihlākiyya", en: "consumerist culture", reg: "msa", topic: "مجتمع", ex: "الثقافة الاستهلاكية خلتنا نقيس قيمة الشي بسعره." },
  { id: "m101", ar: "اختلال", tr: "ikhtilāl", en: "imbalance", reg: "msa", topic: "مجتمع", ex: "اختلال التركيبة السكانية موضوع يتردد بكل ديوانية." },
  { id: "m102", ar: "التركيبة السكانية", tr: "it-tarkība is-sukkāniyya", en: "demographic makeup", reg: "msa", topic: "مجتمع", ex: "تعديل التركيبة السكانية شعار قديم — بس وين الخطة؟" },
  { id: "m103", ar: "التركيب الاقتصادي", tr: "it-tarkīb il-iqtiṣādi", en: "economic structure", reg: "msa", topic: "اقتصاد", ex: "التركيب الاقتصادي عندنا ريعي بالدرجة الأولى." },
  { id: "m104", ar: "يتلاشى", tr: "yatalāsha", en: "to fade away, dissolve", reg: "msa", topic: "نقاش", ex: "الحماس يتلاشى بسرعة إذا ماكو نظام يثبته." },
  { id: "m105", ar: "صراعات", tr: "ṣirāʿāt", en: "conflicts, struggles", reg: "msa", topic: "سياسة", ex: "الصراعات الداخلية تستهلك الفريق أكثر من المنافسين." },
  { id: "m106", ar: "بشاعة", tr: "bashāʿa", en: "ugliness, atrocity", reg: "msa", topic: "نقاش", ex: "ما نقدر نتجاهل بشاعة اللي صار، مهما كانت المبررات." },
  { id: "m107", ar: "جدوى", tr: "jadwa", en: "feasibility, worth", reg: "msa", topic: "اقتصاد", ex: "سوّوا دراسة جدوى قبل لا تحطون فلوسكم بالمشروع.", note: "الإملاء: جدوى (مسجلة عندك «جدوة»)" },
  { id: "m108", ar: "بعين الاعتبار", tr: "b-ʿēn il-iʿtibār", en: "into consideration", reg: "phrase", topic: "نقاش", ex: "خذ بعين الاعتبار إن الصيف عندنا يبطّئ المبيعات." },
  { id: "m109", ar: "بصفة عامة", tr: "bi-ṣifa ʿāmma", en: "generally speaking", reg: "phrase", topic: "نقاش", ex: "بصفة عامة، التجربة نجحت رغم الملاحظات." },
  { id: "m110", ar: "طماشة", tr: "ṭamāsha", en: "a spectacle, something fun to watch", reg: "kw", topic: "يومي", ex: "الجلسة أمس كانت طماشة — ضحك من البداية للنهاية.", note: "كويتية أصيلة — الشي المسلي اللي يتفرج عليه الناس" },
  { id: "m111", ar: "ينفرز", tr: "yinfiriz", en: "gets sorted out, separates", reg: "msa", topic: "نقاش", ex: "وقت الأزمات ينفرز الناس — تعرف منو الصديق الصج." },
  { id: "m112", ar: "شرس", tr: "sharis", en: "fierce, aggressive", reg: "msa", topic: "اقتصاد", ex: "المنافسة بالسوق شرسة — الدخول بدون تميز انتحار." },
  { id: "m113", ar: "الغيرة والحسد", tr: "il-ghīra wil-ḥasad", en: "jealousy and envy", reg: "msa", topic: "مجتمع", ex: "الغيرة ممكن تدفعك تتطور، أما الحسد فياكل صاحبه." },
  { id: "m114", ar: "إدمان", tr: "idmān", en: "addiction", reg: "msa", topic: "مجتمع", ex: "إدمان الأجهزة صار مشكلة حقيقية عند اليهال." },
  { id: "m115", ar: "لعوزكم", tr: "—", en: "(captured — meaning to confirm)", reg: "kw", topic: "يومي", ex: "—", note: "⚠ مسجلة مثل ما سمعتها. يحتمل لها علاقة بجذر «عوز» (الحاجة). اسأل اللي قالها أو كبار العائلة وحدّث البطاقة" },
  { id: "m116", ar: "لو يرجع فيني الزمن", tr: "law yirjaʿ fīni z-ziman", en: "if I could turn back time", reg: "phrase", topic: "يومي", ex: "لو يرجع فيني الزمن، چان بديت أستثمر من أول راتب." },
  { id: "m117", ar: "جوّز عن", tr: "jawwaz ʿan (yōz)", en: "drop it, quit, stop doing", reg: "kw", topic: "يومي", ex: "جوّز عن هالسالفة — ما بتوصلنا لمكان.", note: "كويتية أصيلة، وتنسمع «يوز» بنطق الياء" },
  { id: "m118", ar: "استهدف", tr: "istahdaf", en: "to target, aim at", reg: "msa", topic: "شغل", ex: "الحملة تستهدف شريحة الشباب من ١٨ إلى ٣٠." },
  { id: "m119", ar: "ميزانية", tr: "mīzāniyya", en: "budget", reg: "msa", topic: "اقتصاد", ex: "حط ميزانية لكل شي — حتى للترفيه." },
  { id: "m120", ar: "غموض", tr: "ghumūḍ", en: "ambiguity, vagueness", reg: "msa", topic: "نقاش", ex: "الغموض بالعقد يفتح باب المشاكل — وضّح كل بند." },
  { id: "m121", ar: "ثروة", tr: "tharwa", en: "wealth, fortune", reg: "msa", topic: "اقتصاد", ex: "الثروة الحقيقية للبلد عقول أهلها، مو بس النفط." },
  { id: "m122", ar: "مبادر", tr: "mubādir", en: "one who takes initiative", reg: "msa", topic: "شغل", ex: "كن مبادر — لا تنتظر أحد يعطيك الضوء الأخضر." },
  { id: "m123", ar: "نمو", tr: "numuww", en: "growth", reg: "msa", topic: "اقتصاد", ex: "النمو بدون تخطيط يخلق مشاكل أكبر من اللي يحلها." },
  { id: "m124", ar: "يبادرون", tr: "yubādirūn", en: "they take the initiative", reg: "msa", topic: "شغل", ex: "أحب الفرق اللي يبادرون قبل لا أحد يطلب منهم." },
  { id: "m125", ar: "مناسبة", tr: "munāsaba", en: "occasion; suitable (f.)", reg: "msa", topic: "يومي", ex: "بالمناسبة — عندنا مناسبة عائلية الخميس، لا تنسون." },
  { id: "m126", ar: "عائد", tr: "ʿāʾid", en: "(financial) return", reg: "msa", topic: "اقتصاد", ex: "العائد على العقار أقل، بس المخاطرة بعد أقل." },
  { id: "m127", ar: "أنا كدولة", tr: "ana ka-dawla", en: "\"I, as a state...\" (framing device)", reg: "phrase", topic: "نقاش", ex: "أنا كدولة، وين أحط أولوياتي: التعليم لو البنية التحتية؟", note: "أسلوب نقاش تتقمص فيه دور جهة عشان توضح وجهة نظرها" },
  { id: "m128", ar: "قطاع", tr: "qiṭāʿ", en: "sector", reg: "msa", topic: "اقتصاد", ex: "كل قطاع له تحدياته، بس التعليم أساس الباقي كله." },
  { id: "m129", ar: "مبادرة", tr: "mubādara", en: "initiative", reg: "msa", topic: "شغل", ex: "المبادرة الحلوة تموت إذا ماكو متابعة عقبها." },
  { id: "m130", ar: "فقدنا", tr: "faqadna", en: "we lost", reg: "msa", topic: "نقاش", ex: "فقدنا وايد وقت ونحن نعيد نفس النقطة." },
  { id: "m131", ar: "دولة ريعية", tr: "dawla rayʿiyya", en: "rentier state", reg: "msa", topic: "اقتصاد", ex: "الدولة الريعية تعيش على مورد واحد — وهذا بحد ذاته خطر." },
  { id: "m132", ar: "تضخم", tr: "taḍakhkhum", en: "inflation", reg: "msa", topic: "اقتصاد", ex: "التضخم ياكل من راتبك حتى لو ما حسيت فيه." },
  { id: "m133", ar: "افتراضي", tr: "iftirāḍi", en: "virtual; hypothetical", reg: "msa", topic: "علوم", ex: "الاجتماع بيكون افتراضي — الرابط بالمجموعة." },
  { id: "m134", ar: "طالما", tr: "ṭālama", en: "as long as", reg: "msa", topic: "نقاش", ex: "طالما النتائج زينة، ما عندي مشكلة بالطريقة." },
  { id: "m135", ar: "التبس", tr: "iltabas", en: "became confused / ambiguous", reg: "msa", topic: "نقاش", ex: "التبس علي الموضوع — فهمت العكس تمامًا.", note: "⚠ مسجلة عندك «اتلبس» — الأقرب: التبس عليه الأمر" },
  { id: "m136", ar: "شئنا أم أبينا", tr: "shiʾna am abēna", en: "whether we like it or not", reg: "phrase", topic: "نقاش", ex: "شئنا أم أبينا، الذكاء الاصطناعي بيغير طريقة شغلنا." },
  { id: "m137", ar: "إحباط", tr: "iḥbāṭ", en: "frustration, dejection", reg: "msa", topic: "يومي", ex: "الإحباط عقب الرفض طبيعي — بس لا تخليه يوقفك.", note: "⚠ مسجلة عندك «اهباط» — الأغلب إحباط (وإذا قصدك النزول فهي هبوط)" },
  { id: "m138", ar: "أضطر", tr: "aḍṭarr", en: "I am forced to", reg: "msa", topic: "يومي", ex: "إذا ما تحسن الوضع، بضطر أدور بديل." },
  { id: "m139", ar: "بوابين", tr: "bawwābīn", en: "doormen; gatekeepers (fig.)", reg: "msa", topic: "مجتمع", ex: "بكل مجال أكو «بوابين» يقررون منو يدخل ومنو لا — افهمهم قبل لا تحاربهم." },
  { id: "m140", ar: "ساحل", tr: "sāḥil", en: "coast, shoreline", reg: "msa", topic: "عمران", ex: "إحنا مدينة ساحلية — بس وين الاستغلال الصحيح للساحل؟" },
  { id: "m141", ar: "مقابل / بمقابل", tr: "muqābil", en: "in exchange for", reg: "msa", topic: "اقتصاد", ex: "ماكو شي ببلاش — كل ميزة لها مقابل." },
  { id: "m142", ar: "تستوعب", tr: "tistawʿib", en: "accommodates, absorbs", reg: "msa", topic: "تعليم", ex: "المدارس الحكومية ما عادت تستوعب الأعداد اليديدة." },
  { id: "m143", ar: "مؤرخ", tr: "muʾarrikh", en: "historian", reg: "msa", topic: "ثقافة", ex: "سولفت ويا مؤرخ كويتي عن الفرجان القديمة — سوالف ما تنمل." },
  { id: "m144", ar: "هذا رقم واحد...", tr: "hādha raqam wāḥid", en: "\"that's number one...\" (enumerating)", reg: "phrase", topic: "نقاش", ex: "هذا رقم واحد. ورقم اثنين: التكلفة أقل بالنص." },
  { id: "m145", ar: "تشويه", tr: "tashwīh", en: "distortion, defacing", reg: "msa", topic: "نقاش", ex: "اللي صار تشويه للفكرة الأصلية، مو تطوير لها." },
  { id: "m146", ar: "بحت", tr: "baḥt", en: "pure, sheer (e.g. purely commercial)", reg: "msa", topic: "نقاش", ex: "قراري كان تجاري بحت — ماكو فيه شي شخصي.", note: "مسجلة عندك «بحتي» — تنقال: علمي بحت، تجاري بحت" },
  { id: "m147", ar: "أبسط / بسيط", tr: "absaṭ / basīṭ", en: "simpler / simple", reg: "msa", topic: "نقاش", ex: "نبدأ بأبسط حل ممكن، وعقب نطوره إذا احتجنا." },
  { id: "m148", ar: "تشطيب", tr: "tashṭīb", en: "finishing (construction)", reg: "msa", topic: "عمران", ex: "البيت خلص عظم — باقي التشطيب، وهذا اللي ياكل الميزانية." },
  { id: "m149", ar: "غيّر النظرة", tr: "ghayyar in-naẓra", en: "changed the perception", reg: "phrase", topic: "مجتمع", ex: "شغلك ويا ناس من ثقافات ثانية يغيّر نظرتك للأمور." },
  { id: "m150", ar: "لكن (بدال «بس»)", tr: "lākin", en: "but (elevated register)", reg: "tip", topic: "نقاش", ex: "«الفكرة زينة، لكن تنفيذها يحتاج وقت» — بالنقاش الجاد، «لكن» ترفع مستوى كلامك عن «بس»." },
  { id: "m151", ar: "فكرة ثورية", tr: "fikra thawriyya", en: "revolutionary idea", reg: "msa", topic: "شغل", ex: "مو كل فكرة ثورية تنجح — السوق له كلمته." },
  { id: "m152", ar: "اندثرت", tr: "indatharat", en: "died out, vanished", reg: "msa", topic: "ثقافة", ex: "حِرف قديمة وايد اندثرت، بس أسماؤها باقية بذاكرة كبار السن." },
  { id: "m153", ar: "رعاية", tr: "riʿāya", en: "care; sponsorship", reg: "msa", topic: "شغل", ex: "الفعالية هالسنة تحت رعاية القطاع الخاص." },
  { id: "m154", ar: "ألقاب التخاطب", tr: "astādh / ḥaḍirtak / maʿālīk / sumūk", en: "honorifics: ustādh, ḥaḍirtak, maʿālīk, sumūk", reg: "phrase", topic: "مجاملات", ex: "«أستاذ» للمحترف، «حضرتك» للرسمي، «معاليك» للوزير، «سموك» للشيوخ — اختيار اللقب الصح نص الأدب." },
  { id: "m155", ar: "قارة", tr: "qārra", en: "continent", reg: "msa", topic: "علوم", ex: "أفريقيا قارة الفرص الياية — واللي فاهم دش من الحين." },
  { id: "m156", ar: "متوسط", tr: "mutawassiṭ", en: "average, mean", reg: "msa", topic: "اقتصاد", ex: "الدخل فوق المتوسط، بس التوزيع مو عادل." },
  { id: "m157", ar: "تصدير", tr: "taṣdīr", en: "export", reg: "msa", topic: "اقتصاد", ex: "ليش ما نفكر بتصدير الخدمات بدال ما نعتمد على النفط بس؟" },
  { id: "m158", ar: "إجمالي", tr: "ijmāli", en: "total, gross", reg: "msa", topic: "اقتصاد", ex: "الإجمالي شكله زين — بس التفاصيل تقول شي ثاني." },
  { id: "m159", ar: "قمة", tr: "qimma", en: "summit (meeting or peak)", reg: "msa", topic: "سياسة", ex: "القمة الخليجية طلعت ببيان أقوى من المتوقع." },
  { id: "m160", ar: "تنويع مصادر الدخل", tr: "tanwīʿ maṣādir id-dakhl", en: "diversifying income sources", reg: "msa", topic: "اقتصاد", ex: "تنويع مصادر الدخل مو رفاهية — ضرورة للفرد وللدولة." },
  { id: "m161", ar: "خصوصًا", tr: "khuṣūṣan", en: "especially", reg: "msa", topic: "نقاش", ex: "الحر يأثر على المبيعات، خصوصًا بيوليو وأغسطس." },
  { id: "m162", ar: "تغلّفه", tr: "tughallifah", en: "you wrap / coat it", reg: "msa", topic: "نقاش", ex: "النقد يوصل أحسن إذا تغلّفه بكلمة طيبة." },
  { id: "m163", ar: "الطاقة الشمسية", tr: "iṭ-ṭāqa ish-shamsiyya", en: "solar energy", reg: "msa", topic: "علوم", ex: "الشمس عندنا طول السنة، والطاقة الشمسية بعدها بأولها." },
  { id: "m164", ar: "طاقة الرياح", tr: "ṭāqat ir-riyāḥ", en: "wind energy", reg: "msa", topic: "علوم", ex: "طاقة الرياح تنفع بمناطق معينة — تبي دراسة قبل." },
  { id: "m165", ar: "الطاقة الأحفورية", tr: "iṭ-ṭāqa il-uḥfūriyya", en: "fossil energy", reg: "msa", topic: "علوم", ex: "العالم قاعد يتحول عن الطاقة الأحفورية — وإحنا شنو خطتنا؟" },
  { id: "m166", ar: "ماذا لو / يا ريت", tr: "mādha law / yā rēt", en: "what if / if only", reg: "phrase", topic: "نقاش", ex: "ماذا لو جربنا نموذج مختلف؟ يا ريت نفتح هالباب." },
  { id: "m167", ar: "هذي مو السالفة", tr: "hādhi mū is-sālfa", en: "that's not the point", reg: "kw", topic: "نقاش", ex: "التكلفة مهمة، بس هذي مو السالفة — السالفة بالجودة.", note: "«السالفة» من أكثر الكلمات الكويتية تعبيرًا — الموضوع/القصة" },
  { id: "m168", ar: "دارت الأيام", tr: "dārat il-ayyām", en: "time went by; the tables turned", reg: "phrase", topic: "يومي", ex: "دارت الأيام، واللي كان يتعلم مني صرت أتعلم منه." },
  { id: "m169", ar: "التحقوا", tr: "iltaḥaqaw", en: "they joined, enrolled", reg: "msa", topic: "شغل", ex: "أغلب ربعي التحقوا بالحكومة — وأنا اخترت الخاص." },
  { id: "m170", ar: "توازن", tr: "tawāzun", en: "balance", reg: "msa", topic: "يومي", ex: "التوازن بين الشغل والبيت مهارة تتعلمها، ما تنولد فيها." },
  { id: "m171", ar: "يوجد فرضيات", tr: "yūjad faraḍiyyāt", en: "there are hypotheses", reg: "msa", topic: "علوم", ex: "يوجد فرضيات متعددة، بس ماكو دليل قاطع لحد الحين." },
  { id: "m172", ar: "إطار نظري", tr: "iṭār naẓari", en: "theoretical framework", reg: "msa", topic: "تعليم", ex: "أي بحث محترم يبدأ بإطار نظري واضح." },
  { id: "m173", ar: "القصور الذاتي", tr: "il-quṣūr idh-dhāti", en: "inertia", reg: "msa", topic: "علوم", ex: "القصور الذاتي مو بس بالفيزياء — المؤسسات بعد تقاوم الحركة." },
  { id: "m174", ar: "الاحتمالات", tr: "il-iḥtimālāt", en: "the probabilities, possibilities", reg: "msa", topic: "علوم", ex: "نرتب الاحتمالات من الأقرب للأبعد، ونخطط على أساسها." },
  { id: "m175", ar: "تعصب", tr: "taʿaṣṣub", en: "bigotry, fanaticism", reg: "msa", topic: "مجتمع", ex: "التعصب يقفل باب النقاش قبل لا يبدأ." },
  { id: "m176", ar: "مجاورة", tr: "mujāwara", en: "adjacent, neighboring", reg: "msa", topic: "عمران", ex: "المناطق المجاورة للمشروع أول اللي ترتفع أسعارها." },
  { id: "m177", ar: "ضمير", tr: "ḍamīr", en: "conscience", reg: "msa", topic: "مجتمع", ex: "بالآخر، ضميرك هو الرقيب اللي ما ينام." },
  { id: "m178", ar: "تعويض / تعويضات", tr: "taʿwīḍ / taʿwīḍāt", en: "compensation", reg: "msa", topic: "اقتصاد", ex: "تعويضات ما بعد الغزو قصة طويلة بتاريخ الكويت." },
  { id: "m179", ar: "وثيقة", tr: "wathīqa", en: "document, deed", reg: "msa", topic: "شغل", ex: "لا توقع أي وثيقة قبل لا تقراها كلمة كلمة." },
  { id: "m180", ar: "معاونة", tr: "muʿāwana", en: "assistance, aid", reg: "msa", topic: "مجاملات", ex: "قدموا لنا معاونة كبيرة أول ما بدينا — هالشي ما ينتسى." },
  { id: "m181", ar: "ممتص الصدمات", tr: "mumtaṣṣ iṣ-ṣadamāt", en: "shock absorber (lit. & fig.)", reg: "phrase", topic: "شغل", ex: "المدير الزين ممتص صدمات — يحمي فريقه من الضغط اللي فوقه." },
  { id: "m182", ar: "لِيومك هذا", tr: "li-yōmik hādha", en: "to this very day", reg: "phrase", topic: "يومي", ex: "نصحني قبل عشر سنين، ولِيومك هذا أطبق كلامه.", note: "⚠ مسجلة عندك «لي يومك» — أكد الصيغة اللي سمعتها" },
  { id: "m183", ar: "الأدب", tr: "al-adab", en: "literature; manners", reg: "msa", topic: "ثقافة", ex: "الأدب الكويتي فيه أسماء تستاهل تنقرا أكثر." },
  { id: "m184", ar: "نطق", tr: "nuṭq", en: "pronunciation, utterance", reg: "msa", topic: "تعليم", ex: "النطق السليم للمصطلح نص هيبته." },
  { id: "m185", ar: "خثاق", tr: "khaththāg", en: "cuttlefish", reg: "kw", topic: "بحر وتراث", ex: "يوم رحنا الحداق، أغلب اللي طلع لنا خثاق مو هامور.", note: "من مفردات البحر الكويتية — والحبر ماله يستخدم بالطبخ" },
  { id: "m186", ar: "اصطلاحات", tr: "iṣṭilāḥāt", en: "conventions, idioms of a group", reg: "msa", topic: "ثقافة", ex: "لكل ديوانية اصطلاحاتها اللي ما يفهمها إلا أهلها." },
  { id: "m187", ar: "آمون عليه", tr: "āmūn ʿalēh", en: "I can count on him / impose on him freely", reg: "kw", topic: "مجاملات", ex: "خالد آمون عليه — أطلبه أي وقت وما يردني.", note: "كويتية — من الأمانة والثقة: الشخص اللي تطلبه بلا تردد" },
  { id: "m188", ar: "بهرجة", tr: "bahraja", en: "flashiness, glitz", reg: "msa", topic: "مجتمع", ex: "العرس كله بهرجة، بس المضمون بسيط." },
  { id: "m189", ar: "مهجورة", tr: "mahjūra", en: "abandoned, deserted", reg: "msa", topic: "عمران", ex: "بيوت الفريج القديم مهجورة، وكل بيت وراه قصة." },
  { id: "m190", ar: "نطاق", tr: "niṭāq", en: "range, scope, spectrum", reg: "msa", topic: "نقاش", ex: "هالموضوع خارج نطاق الاجتماع — نفتح له جلسة ثانية.", note: "الإملاء: نطاق (مسجلة عندك «نيطاق»)" },
  { id: "m191", ar: "مناخ", tr: "munākh", en: "climate (weather & fig.)", reg: "msa", topic: "علوم", ex: "مناخنا قاسي بالصيف — والتخطيط لازم يحترم هالحقيقة." },
  { id: "m192", ar: "جاف", tr: "jāff", en: "dry (climate; tone)", reg: "msa", topic: "يومي", ex: "رده كان جاف شوي — حسيت إنه مو مرتاح للفكرة." },
  { id: "m193", ar: "طب / طبة", tr: "ṭabb / ṭabba", en: "(captured — meaning to confirm)", reg: "kw", topic: "يومي", ex: "—", note: "⚠ مسجلة «طب طبة». «طبّ» بالكويتي = دش أو نط فجأة (طبّ البحر، طبّ علينا بالديوانية). أكد المعنى من السياق اللي سمعته فيه" },
  { id: "m194", ar: "مياديف", tr: "mayādīf", en: "oars (sg. مِيداف)", reg: "kw", topic: "بحر وتراث", ex: "قبل المكاين، البحّارة ما لهم إلا المياديف والشراع.", note: "من التراث البحري الكويتي" },
  { id: "m195", ar: "ما تنأخذ بالذراع", tr: "mā tinʾakhadh bidh-dhirāʿ", en: "it can't be forced (by strength)", reg: "phrase", topic: "نقاش", ex: "هالسالفة ما تنأخذ بالذراع — تبي لها صبر وحكمة.", note: "⚠ مسجلة عندك «تأخذها بذراعك» — تنقال غالبًا بالنفي" },
  { id: "m196", ar: "مؤيد ومعارض", tr: "muʾayyid u-muʿāriḍ", en: "for and against (sides of a debate)", reg: "msa", topic: "نقاش", ex: "كل قضية لها مؤيد ومعارض — المهم مستوى الحجة، مو علو الصوت." },
];
