/*
 * SEED_DOMAINS — professional-domain packs. Same card shape as SEED_PACKS
 * and merged into it at load, so they behave like any other pack: inert
 * until added from الحزم.
 *
 * These are MSA technical terms as they are actually used inside educated
 * Kuwaiti speech — tagged "msa" for that reason. Every example sentence is
 * written in Kuwaiti dialect, because that is the frame you will use them in.
 */
const SEED_DOMAINS = [
  {
    key: "space",
    name: "فضاء وطيران",
    nameEn: "Space & aerospace",
    desc: "مصطلحات الفضاء والطيران — من الإقلاع إلى المدار. مبنية بدقة، مو مثل القوائم القديمة.",
    descEn: "Space and aerospace terminology — from takeoff to orbit. Built carefully, unlike the old lists.",
    words: [
      { id: "sp01", ar: "مدار", tr: "madār", en: "orbit", reg: "msa", topic: "فضاء", ex: "القمر الصناعي دخل مداره بنجاح عقب ثلاث ساعات من الإطلاق." },
      { id: "sp02", ar: "الغلاف الجوي", tr: "il-ghilāf il-jawwi", en: "the atmosphere", reg: "msa", topic: "فضاء", ex: "الغلاف الجوي هو اللي يحمينا من الأشعة والنيازك." },
      { id: "sp03", ar: "انعدام الوزن", tr: "inʿidām il-wazn", en: "weightlessness", reg: "msa", topic: "فضاء", ex: "انعدام الوزن يأثر على العظام والعضلات، فرواد الفضاء لازم يتمرنون كل يوم." },
      { id: "sp04", ar: "سرعة الإفلات", tr: "surʿat il-iflāt", en: "escape velocity", reg: "msa", topic: "فضاء", ex: "لازم توصل سرعة الإفلات عشان تتحرر من جاذبية الأرض." },
      { id: "sp05", ar: "الدفع", tr: "id-dafʿ", en: "thrust", reg: "msa", topic: "فضاء", ex: "الدفع لازم يتجاوز الوزن، وإلا الصاروخ ما يرتفع." },
      { id: "sp06", ar: "وقود دافع", tr: "waqūd dāfiʿ", en: "propellant", reg: "msa", topic: "فضاء", ex: "أغلب وزن الصاروخ عند الإقلاع وقود دافع، مو حمولة." },
      { id: "sp07", ar: "منصة الإطلاق", tr: "minaṣṣat il-iṭlāq", en: "launch pad", reg: "msa", topic: "فضاء", ex: "وقفوا العد التنازلي وهم على منصة الإطلاق بسبب الرياح." },
      { id: "sp08", ar: "العد التنازلي", tr: "il-ʿadd it-tanāzuli", en: "the countdown", reg: "msa", topic: "فضاء", ex: "العد التنازلي ينوقف بأي لحظة إذا طلعت قراءة غريبة." },
      { id: "sp09", ar: "إعادة الدخول", tr: "iʿādat id-dukhūl", en: "re-entry", reg: "msa", topic: "فضاء", ex: "إعادة الدخول أخطر من الإقلاع — الحرارة توصل آلاف الدرجات." },
      { id: "sp10", ar: "درع حراري", tr: "dirʿ ḥarāri", en: "heat shield", reg: "msa", topic: "فضاء", ex: "بدون درع حراري سليم، المركبة تحترق قبل لا توصل." },
      { id: "sp11", ar: "المدار الأرضي المنخفض", tr: "il-madār il-arḍi il-munkhafiḍ", en: "low Earth orbit (LEO)", reg: "msa", topic: "فضاء", ex: "أغلب الأقمار التجارية تشتغل بالمدار الأرضي المنخفض." },
      { id: "sp12", ar: "محطة الفضاء الدولية", tr: "maḥaṭṭat il-faḍāʾ id-dawliyya", en: "the International Space Station", reg: "msa", topic: "فضاء", ex: "محطة الفضاء الدولية أكبر مشروع تعاون علمي بالتاريخ." },
      { id: "sp13", ar: "بدلة الفضاء", tr: "badlat il-faḍāʾ", en: "spacesuit", reg: "msa", topic: "فضاء", ex: "بدلة الفضاء بحد ذاتها مركبة صغيرة — ضغط وأكسجين وتبريد." },
      { id: "sp14", ar: "السير في الفضاء", tr: "is-sayr fi l-faḍāʾ", en: "spacewalk (EVA)", reg: "msa", topic: "فضاء", ex: "أي مهمة سير في الفضاء تتدرب عليها شهور تحت الماي." },
      { id: "sp15", ar: "الطاقم", tr: "iṭ-ṭāqim", en: "the crew", reg: "msa", topic: "فضاء", ex: "الطاقم كله لازم يعرف يسوي شغل غيره — ماكو أحد ما ينعوض." },
      { id: "sp16", ar: "الديناميكا الهوائية", tr: "id-dīnāmīka il-hawāʾiyya", en: "aerodynamics", reg: "msa", topic: "فضاء", ex: "شكل الجناح كله حسابات ديناميكا هوائية، مو ذوق." },
      { id: "sp17", ar: "قوة الرفع", tr: "quwwat ir-rafʿ", en: "lift", reg: "msa", topic: "فضاء", ex: "قوة الرفع تيي من فرق الضغط فوق الجناح وتحته." },
      { id: "sp18", ar: "مقاومة الهواء", tr: "muqāwamat il-hawa", en: "drag", reg: "msa", topic: "فضاء", ex: "كل ما قللت مقاومة الهواء، قل استهلاك الوقود." },
      { id: "sp19", ar: "الاضطرابات الجوية", tr: "il-iḍṭirābāt il-jawwiyya", en: "turbulence", reg: "msa", topic: "فضاء", ex: "الاضطرابات الجوية مزعجة بس نادرًا تكون خطرة." },
      { id: "sp20", ar: "تفوق سرعة الصوت", tr: "tafawwuq surʿat iṣ-ṣōt", en: "supersonic", reg: "msa", topic: "فضاء", ex: "الطيران بتفوق سرعة الصوت رجع يتطور من يديد." },
      { id: "sp21", ar: "الطيار الآلي", tr: "iṭ-ṭayyār il-āli", en: "autopilot", reg: "msa", topic: "فضاء", ex: "الطيار الآلي يمسك أغلب الرحلة، بس الإقلاع والهبوط للبشر." },
      { id: "sp22", ar: "برج المراقبة", tr: "burj il-murāqaba", en: "control tower", reg: "msa", topic: "فضاء", ex: "ماكو إقلاع بدون إذن من برج المراقبة." },
      { id: "sp23", ar: "السنة الضوئية", tr: "is-sana iḍ-ḍōʾiyya", en: "light year", reg: "msa", topic: "فضاء", ex: "السنة الضوئية وحدة مسافة مو زمن — وهذي أشهر غلطة." },
      { id: "sp24", ar: "الثقب الأسود", tr: "ith-thugub il-aswad", en: "black hole", reg: "msa", topic: "فضاء", ex: "الثقب الأسود جاذبيته قوية لدرجة إن الضوء ما يفلت منه." },
      { id: "sp25", ar: "المرصد", tr: "il-marṣad", en: "observatory", reg: "msa", topic: "فضاء", ex: "المرصد لازم يكون بعيد عن أضواء المدينة." },
      { id: "sp26", ar: "الكويكب", tr: "il-kuwaykib", en: "asteroid", reg: "msa", topic: "فضاء", ex: "أكو كويكبات فيها معادن تسوى أكثر من اقتصادات كاملة." },
      { id: "sp27", ar: "المذنّب", tr: "il-mudhannab", en: "comet", reg: "msa", topic: "فضاء", ex: "ذيل المذنّب يطول كل ما قرّب من الشمس." },
      { id: "sp28", ar: "الكسوف والخسوف", tr: "il-kusūf wil-khusūf", en: "solar & lunar eclipse", reg: "msa", topic: "فضاء", ex: "الكسوف للشمس والخسوف للقمر — والناس تخلطهم وايد." },
    ],
  },
  {
    key: "science",
    name: "علوم وفيزياء",
    nameEn: "Science & physics",
    desc: "لغة العلم بالعربي — تنفع بالنقاش الجاد وبقراءة أي شي علمي بلغتك.",
    descEn: "The language of science in Arabic — for serious discussion and for reading science in your own language.",
    words: [
      { id: "sc01", ar: "فرضية", tr: "faraḍiyya", en: "hypothesis", reg: "msa", topic: "علوم", ex: "الفرضية بدون تجربة تظل رأي، مو علم." },
      { id: "sc02", ar: "نظرية", tr: "naẓariyya", en: "theory (scientific)", reg: "msa", topic: "علوم", ex: "بالعلم، «نظرية» يعني مثبتة بأدلة — مو مجرد تخمين." },
      { id: "sc03", ar: "التجربة الضابطة", tr: "it-tajruba iḍ-ḍābiṭa", en: "control experiment", reg: "msa", topic: "علوم", ex: "بدون تجربة ضابطة، ما تعرف إذا النتيجة من العلاج ولا من الصدفة." },
      { id: "sc04", ar: "العينة", tr: "il-ʿayyina", en: "sample", reg: "msa", topic: "علوم", ex: "العينة صغيرة، فالنتيجة ما تتعمم على الكل." },
      { id: "sc05", ar: "الارتباط لا يعني السببية", tr: "il-irtibāṭ lā yaʿni is-sababiyya", en: "correlation is not causation", reg: "phrase", topic: "علوم", ex: "الرقمين يتحركون مع بعض، بس الارتباط لا يعني السببية." },
      { id: "sc06", ar: "الذرة", tr: "idh-dharra", en: "atom", reg: "msa", topic: "علوم", ex: "الذرة أغلبها فراغ — وهذي حقيقة تغير نظرتك للمادة." },
      { id: "sc07", ar: "الجزيء", tr: "il-juzayʾ", en: "molecule", reg: "msa", topic: "علوم", ex: "جزيء الماي ذرتين هيدروجين وذرة أكسجين." },
      { id: "sc08", ar: "الاندماج النووي", tr: "il-indimāj in-nawawi", en: "nuclear fusion", reg: "msa", topic: "علوم", ex: "الاندماج النووي هو اللي يشغل الشمس من ملايين السنين." },
      { id: "sc09", ar: "الانشطار النووي", tr: "il-inshiṭār in-nawawi", en: "nuclear fission", reg: "msa", topic: "علوم", ex: "المفاعلات الحالية كلها تشتغل بالانشطار، مو بالاندماج." },
      { id: "sc10", ar: "النسبية", tr: "in-nisbiyya", en: "relativity", reg: "msa", topic: "علوم", ex: "النسبية تقول إن الزمن نفسه يتغير حسب السرعة والجاذبية." },
      { id: "sc11", ar: "ميكانيكا الكم", tr: "mīkānīka il-kamm", en: "quantum mechanics", reg: "msa", topic: "علوم", ex: "ميكانيكا الكم تشتغل صح حتى لو ما أحد فاهم ليش." },
      { id: "sc12", ar: "الطيف", tr: "iṭ-ṭayf", en: "spectrum", reg: "msa", topic: "علوم", ex: "من طيف الضوء نعرف تركيب نجم يبعد ملايين السنين." },
      { id: "sc13", ar: "التحفيز", tr: "it-taḥfīz", en: "catalysis", reg: "msa", topic: "علوم", ex: "المحفّز يسرّع التفاعل بدون ما يستهلك نفسه." },
      { id: "sc14", ar: "الكثافة", tr: "il-kathāfa", en: "density", reg: "msa", topic: "علوم", ex: "الحديد أثقل من الخشب بنفس الحجم لأن كثافته أعلى." },
      { id: "sc15", ar: "اللزوجة", tr: "il-luzūja", en: "viscosity", reg: "msa", topic: "علوم", ex: "لزوجة الزيت تتغير بالحرارة، وهذا مهم بالمحركات." },
      { id: "sc16", ar: "الاحتكاك", tr: "il-iḥtikāk", en: "friction (physics)", reg: "msa", topic: "علوم", ex: "بدون احتكاك ما تقدر تمشي ولا توقف سيارة." },
      { id: "sc17", ar: "الزخم", tr: "iz-zakham", en: "momentum", reg: "msa", topic: "علوم", ex: "الزخم محفوظ — هذا اللي يفسر ارتداد البندقية." },
      { id: "sc18", ar: "التسارع", tr: "it-tasāruʿ", en: "acceleration", reg: "msa", topic: "علوم", ex: "التسارع تغيّر بالسرعة، مو السرعة نفسها." },
      { id: "sc19", ar: "الموصل والعازل", tr: "il-mūṣil wil-ʿāzil", en: "conductor and insulator", reg: "msa", topic: "علوم", ex: "النحاس موصل ممتاز، والمطاط عازل — والفرق بينهم ينقذ أرواح." },
      { id: "sc20", ar: "التمثيل الضوئي", tr: "it-tamthīl iḍ-ḍōʾi", en: "photosynthesis", reg: "msa", topic: "علوم", ex: "التمثيل الضوئي هو اللي يحوّل ضوء الشمس إلى غذاء." },
      { id: "sc21", ar: "الأيض", tr: "il-ayḍ", en: "metabolism", reg: "msa", topic: "علوم", ex: "الأيض يختلف من شخص لشخص، وهذا ليش الحميات ما تنفع الكل." },
      { id: "sc22", ar: "المناعة", tr: "il-manāʿa", en: "immunity", reg: "msa", topic: "علوم", ex: "المناعة تتعلم — وهذا مبدأ التطعيم كله." },
      { id: "sc23", ar: "الجينات", tr: "il-jīnāt", en: "genes", reg: "msa", topic: "علوم", ex: "الجينات تعطيك الاحتمالات، والبيئة تحدد النتيجة." },
      { id: "sc24", ar: "الطفرة", tr: "iṭ-ṭafra", en: "mutation", reg: "msa", topic: "علوم", ex: "أغلب الطفرات ما تسوي شي، وقليل منها يغيّر كل شي." },
      { id: "sc25", ar: "البيانات التجريبية", tr: "il-bayānāt it-tajrībiyya", en: "empirical data", reg: "msa", topic: "علوم", ex: "أنا ما أجادل بالرأي — عطني بيانات تجريبية." },
      { id: "sc26", ar: "مراجعة الأقران", tr: "murājaʿat il-aqrān", en: "peer review", reg: "msa", topic: "علوم", ex: "أي بحث ما مرّ على مراجعة الأقران، خذه بحذر." },
      { id: "sc27", ar: "قابلية التكرار", tr: "qābiliyyat it-takrār", en: "reproducibility", reg: "msa", topic: "علوم", ex: "إذا التجربة ما تنعاد بنفس النتيجة، فيها شي غلط." },
      { id: "sc28", ar: "هامش الخطأ", tr: "hāmish il-khaṭaʾ", en: "margin of error", reg: "msa", topic: "علوم", ex: "الفرق بين النسبتين داخل هامش الخطأ — يعني ما يعني شي." },
    ],
  },
  {
    key: "finance",
    name: "مال واستثمار",
    nameEn: "Finance & investment",
    desc: "لغة المال بالعربي — من قراءة ميزانية إلى نقاش استثمار بمجلس.",
    descEn: "The language of money in Arabic — from reading a balance sheet to holding an investment conversation.",
    words: [
      { id: "fn01", ar: "السيولة", tr: "is-suyūla", en: "liquidity", reg: "msa", topic: "مال", ex: "الشركة مرابحة على الورق، بس ماكو عندها سيولة تدفع فيها الرواتب." },
      { id: "fn02", ar: "الأصول والخصوم", tr: "il-uṣūl wil-khuṣūm", en: "assets and liabilities", reg: "msa", topic: "مال", ex: "أول شي أشوفه بأي شركة: الأصول مقابل الخصوم." },
      { id: "fn03", ar: "حقوق الملكية", tr: "ḥuqūq il-milkiyya", en: "equity", reg: "msa", topic: "مال", ex: "حقوق الملكية هي اللي يظل لك عقب ما تسدد كل الديون." },
      { id: "fn04", ar: "التدفق النقدي", tr: "it-tadaffuq in-naqdi", en: "cash flow", reg: "msa", topic: "مال", ex: "الشركات تموت من التدفق النقدي، مو من قلة الأرباح." },
      { id: "fn05", ar: "صافي الربح", tr: "ṣāfi ir-ribḥ", en: "net profit", reg: "msa", topic: "مال", ex: "لا تنبهر بالإيرادات — قل لي شكثر صافي الربح." },
      { id: "fn06", ar: "هامش الربح", tr: "hāmish ir-ribḥ", en: "profit margin", reg: "msa", topic: "مال", ex: "المبيعات زادت بس هامش الربح نزل — يعني نبيع أكثر ونكسب أقل." },
      { id: "fn07", ar: "العائد على الاستثمار", tr: "il-ʿāʾid ʿala l-istithmār", en: "return on investment (ROI)", reg: "msa", topic: "مال", ex: "العائد على الاستثمار حلو، بس شنو المخاطرة اللي وراه؟" },
      { id: "fn08", ar: "رأس المال العامل", tr: "raʾs il-māl il-ʿāmil", en: "working capital", reg: "msa", topic: "مال", ex: "رأس المال العامل هو اللي يخليك تشتغل يوم بيوم." },
      { id: "fn09", ar: "التقييم", tr: "it-taqyīm", en: "valuation", reg: "msa", topic: "مال", ex: "تقييم الشركة مبني على توقعات، وهني بالضبط الخطر." },
      { id: "fn10", ar: "الطرح العام الأولي", tr: "iṭ-ṭarḥ il-ʿāmm il-awwali", en: "IPO", reg: "msa", topic: "مال", ex: "قررت الشركة تدش الطرح العام الأولي السنة الياية." },
      { id: "fn11", ar: "الاندماج والاستحواذ", tr: "il-indimāj wil-istiḥwādh", en: "mergers & acquisitions", reg: "msa", topic: "مال", ex: "أغلب صفقات الاندماج والاستحواذ ما تحقق اللي وعدوا فيه." },
      { id: "fn12", ar: "التنويع", tr: "it-tanwīʿ", en: "diversification", reg: "msa", topic: "مال", ex: "التنويع مو عشان تربح أكثر — عشان ما تخسر كل شي مرة وحدة." },
      { id: "fn13", ar: "المحفظة", tr: "il-maḥfaẓa", en: "portfolio", reg: "msa", topic: "مال", ex: "محفظتي كلها قطاع واحد — وهذي غلطة أعرفها." },
      { id: "fn14", ar: "التحوّط", tr: "it-taḥawwuṭ", en: "hedging", reg: "msa", topic: "مال", ex: "التحوّط يقلل الربح المتوقع مقابل إنه يحميك من الانهيار." },
      { id: "fn15", ar: "التقلّب", tr: "it-taqallub", en: "volatility", reg: "msa", topic: "مال", ex: "التقلّب مو خسارة — بس أعصاب الناس ما تتحمله." },
      { id: "fn16", ar: "الرافعة المالية", tr: "ir-rāfiʿa il-māliyya", en: "leverage", reg: "msa", topic: "مال", ex: "الرافعة المالية تكبّر الربح والخسارة بنفس النسبة — لا تنسى النص الثاني." },
      { id: "fn17", ar: "الفائدة المركبة", tr: "il-fāʾida il-murakkaba", en: "compound interest", reg: "msa", topic: "مال", ex: "الفائدة المركبة أقوى شي بالاستثمار — بس تبي وقت." },
      { id: "fn18", ar: "الركود", tr: "ir-rukūd", en: "recession", reg: "msa", topic: "مال", ex: "بأوقات الركود، اللي عنده سيولة يشتري بأسعار ما تتكرر." },
      { id: "fn19", ar: "التوزيعات", tr: "it-tawzīʿāt", en: "dividends", reg: "msa", topic: "مال", ex: "أفضل أسهم التوزيعات — تعطيني دخل بدون ما أبيع." },
      { id: "fn20", ar: "القيمة السوقية", tr: "il-qīma is-sūqiyya", en: "market capitalization", reg: "msa", topic: "مال", ex: "القيمة السوقية ما تقول لك إذا الشركة رخيصة ولا غالية." },
      { id: "fn21", ar: "الميزانية العمومية", tr: "il-mīzāniyya il-ʿumūmiyya", en: "balance sheet", reg: "msa", topic: "مال", ex: "اقرا الميزانية العمومية قبل لا تسمع عرض أي أحد." },
      { id: "fn22", ar: "التدقيق", tr: "it-tadqīq", en: "audit", reg: "msa", topic: "مال", ex: "التدقيق المستقل مو رفاهية — هو اللي يحمي المساهم." },
      { id: "fn23", ar: "الإفصاح", tr: "il-ifṣāḥ", en: "disclosure", reg: "msa", topic: "مال", ex: "ضعف الإفصاح أول علامة إن أكو شي مخبى." },
      { id: "fn24", ar: "الحوكمة", tr: "il-ḥawkama", en: "corporate governance", reg: "msa", topic: "مال", ex: "الحوكمة الزينة تخلي الشركة تكبر بدون ما تعتمد على شخص واحد." },
      { id: "fn25", ar: "الامتثال", tr: "il-imtithāl", en: "compliance", reg: "msa", topic: "مال", ex: "الامتثال مكلف، بس مخالفته أغلى بوايد." },
      { id: "fn26", ar: "الصندوق السيادي", tr: "iṣ-ṣundūq is-siyādi", en: "sovereign wealth fund", reg: "msa", topic: "مال", ex: "الصندوق السيادي الكويتي من أقدم الصناديق بالعالم." },
      { id: "fn27", ar: "المضاربة", tr: "il-muḍāraba", en: "speculation", reg: "msa", topic: "مال", ex: "الفرق بين الاستثمار والمضاربة: الأول يشتري قيمة، والثاني يشتري حركة." },
      { id: "fn28", ar: "الأصول المدرّة للدخل", tr: "il-uṣūl il-mudirra lid-dakhl", en: "income-generating assets", reg: "phrase", topic: "مال", ex: "الثروة الحقيقية أصول مدرّة للدخل، مو أشياء تلمع." },
    ],
  },
  {
    key: "politics",
    name: "سياسة ودستور",
    nameEn: "Politics & constitution",
    desc: "لغة السياسة والدستور — مصطلحات تسمعها بمجلس الأمة وبأي ديوانية جادة.",
    descEn: "The language of politics and the constitution — terms you'll hear in the National Assembly and in any serious diwaniya.",
    words: [
      { id: "pl01", ar: "الدستور", tr: "id-dustūr", en: "the constitution", reg: "msa", topic: "سياسة", ex: "الدستور الكويتي من ١٩٦٢، ولين الحين هو المرجع." },
      { id: "pl02", ar: "الفصل بين السلطات", tr: "il-faṣl bēn is-suluṭāt", en: "separation of powers", reg: "phrase", topic: "سياسة", ex: "الفصل بين السلطات هو اللي يمنع تركّز القرار بيد وحدة." },
      { id: "pl03", ar: "السلطة التشريعية", tr: "is-sulṭa it-tashrīʿiyya", en: "the legislative branch", reg: "msa", topic: "سياسة", ex: "السلطة التشريعية تشرّع وتراقب، والتنفيذية تنفّذ." },
      { id: "pl04", ar: "مرسوم", tr: "marsūm", en: "decree", reg: "msa", topic: "سياسة", ex: "صدر مرسوم بحل المجلس، والانتخابات خلال شهرين." },
      { id: "pl05", ar: "اللائحة", tr: "il-lāʾiḥa", en: "bylaw, regulations", reg: "msa", topic: "سياسة", ex: "القانون شي واللائحة التنفيذية شي — والشيطان بالتفاصيل." },
      { id: "pl06", ar: "طرح الثقة", tr: "ṭarḥ ith-thiqa", en: "vote of no confidence", reg: "phrase", topic: "سياسة", ex: "عقب الاستجواب، أكو نواب طالبوا بطرح الثقة." },
      { id: "pl07", ar: "النصاب", tr: "in-niṣāb", en: "quorum", reg: "msa", topic: "سياسة", ex: "الجلسة ما انعقدت لأن النصاب ما اكتمل." },
      { id: "pl08", ar: "الدائرة الانتخابية", tr: "id-dāʾira il-intikhābiyya", en: "electoral constituency", reg: "msa", topic: "سياسة", ex: "تقسيم الدوائر الانتخابية يغيّر النتيجة قبل لا يصوّت أحد." },
      { id: "pl09", ar: "المساءلة", tr: "il-musāʾala", en: "accountability", reg: "msa", topic: "سياسة", ex: "بدون مساءلة، أحسن قانون يظل حبر على ورق." },
      { id: "pl10", ar: "الشفافية", tr: "ish-shafāfiyya", en: "transparency", reg: "msa", topic: "سياسة", ex: "الشفافية أرخص وسيلة لمحاربة الفساد." },
      { id: "pl11", ar: "المحسوبية", tr: "il-maḥsūbiyya", en: "nepotism, favoritism", reg: "msa", topic: "سياسة", ex: "المحسوبية تطلّع الكفاءات برى وتخلي الشاطر يهاجر." },
      { id: "pl12", ar: "واسطة", tr: "wāsṭa", en: "wasta — connections used to get things done", reg: "kw", topic: "سياسة", ex: "المشكلة مو إن أكو واسطة — المشكلة إنها صارت الطريق الوحيد." },
      { id: "pl13", ar: "البيروقراطية", tr: "il-bīrūqrāṭiyya", en: "bureaucracy", reg: "msa", topic: "سياسة", ex: "البيروقراطية تقتل أي مبادرة قبل لا تبدأ." },
      { id: "pl14", ar: "السيادة", tr: "is-siyāda", en: "sovereignty", reg: "msa", topic: "سياسة", ex: "السيادة مو شعار — هي قدرتك تاخذ قرارك بدون ضغط." },
      { id: "pl15", ar: "الدبلوماسية", tr: "id-diblūmāsiyya", en: "diplomacy", reg: "msa", topic: "سياسة", ex: "الكويت بنت سمعتها على الدبلوماسية والوساطة، مو على القوة." },
      { id: "pl16", ar: "الوساطة", tr: "il-wisāṭa", en: "mediation (between parties)", reg: "msa", topic: "سياسة", ex: "دور الوساطة يحتاج ثقة الطرفين — وهذا اللي ميّز الكويت." },
      { id: "pl17", ar: "المعاهدة", tr: "il-muʿāhada", en: "treaty", reg: "msa", topic: "سياسة", ex: "المعاهدة ما تصير نافذة إلا عقب ما يصادق عليها المجلس." },
      { id: "pl18", ar: "العقوبات", tr: "il-ʿuqūbāt", en: "sanctions", reg: "msa", topic: "سياسة", ex: "العقوبات الاقتصادية سلاح بطيء وأثره يوصل للناس قبل الحكام." },
      { id: "pl19", ar: "الحياد", tr: "il-ḥiyād", en: "neutrality", reg: "msa", topic: "سياسة", ex: "الحياد موقف بحد ذاته، مو غياب موقف." },
      { id: "pl20", ar: "الإجماع", tr: "il-ijmāʿ", en: "consensus", reg: "msa", topic: "سياسة", ex: "وصلوا لإجماع عقب جلسات طويلة — وهذا نادر." },
      { id: "pl21", ar: "التصعيد والتهدئة", tr: "it-taṣʿīd wit-tahdiʾa", en: "escalation and de-escalation", reg: "phrase", topic: "سياسة", ex: "كل طرف يهدد بالتصعيد وهو يبي التهدئة — هذي لعبة قديمة." },
      { id: "pl22", ar: "الرأي المخالف", tr: "ir-raʾy il-mukhālif", en: "dissenting opinion", reg: "phrase", topic: "سياسة", ex: "الرأي المخالف يقوّي القرار إذا انسمع، ويضعفه إذا انقمع." },
      { id: "pl23", ar: "الشرعية", tr: "ish-sharʿiyya", en: "legitimacy", reg: "msa", topic: "سياسة", ex: "الشرعية تيي من رضا الناس، مو من القوة." },
      { id: "pl24", ar: "المصلحة العامة", tr: "il-maṣlaḥa il-ʿāmma", en: "the public interest", reg: "phrase", topic: "سياسة", ex: "كل واحد يتكلم باسم المصلحة العامة، والمقصود مصلحته." },
      { id: "pl25", ar: "تضارب المصالح", tr: "taḍārub il-maṣāliḥ", en: "conflict of interest", reg: "phrase", topic: "سياسة", ex: "أكو تضارب مصالح واضح: هو اللي يقرر وهو اللي يستفيد." },
      { id: "pl26", ar: "الرقابة", tr: "ir-riqāba", en: "oversight", reg: "msa", topic: "سياسة", ex: "الرقابة المسبقة تعطّل، والرقابة اللاحقة تحاسب — والفرق كبير." },
      { id: "pl27", ar: "التداول السلمي للسلطة", tr: "it-tadāwul is-silmi lis-sulṭa", en: "peaceful transfer of power", reg: "phrase", topic: "سياسة", ex: "التداول السلمي للسلطة هو الاختبار الحقيقي لأي نظام." },
      { id: "pl28", ar: "الدولة المؤسسية", tr: "id-dawla il-muʾassasiyya", en: "the institutional state", reg: "phrase", topic: "سياسة", ex: "الدولة المؤسسية ما تعتمد على أشخاص — تعتمد على أنظمة." },
    ],
  },
  {
    key: "engineering",
    name: "هندسة وتنفيذ",
    nameEn: "Engineering & delivery",
    desc: "مصطلحات الهندسة والتنفيذ — تنفعك بأي اجتماع مشروع، من التصميم للتسليم.",
    descEn: "Engineering and delivery terminology — for any project meeting, from design to handover.",
    words: [
      { id: "eg01", ar: "المواصفات", tr: "il-muwāṣafāt", en: "specifications", reg: "msa", topic: "هندسة", ex: "المواصفات لازم تكون مكتوبة، وإلا كل واحد بيفهمها على كيفه." },
      { id: "eg02", ar: "النموذج الأولي", tr: "in-namūdhaj il-awwali", en: "prototype", reg: "msa", topic: "هندسة", ex: "نبني نموذج أولي بسيط قبل لا نصرف على التصنيع." },
      { id: "eg03", ar: "دراسة الجدوى الفنية", tr: "dirāsat il-jadwa il-fanniyya", en: "technical feasibility study", reg: "phrase", topic: "هندسة", ex: "دراسة الجدوى الفنية توفّر عليك سنة ضياع." },
      { id: "eg04", ar: "نطاق العمل", tr: "niṭāq il-ʿamal", en: "scope of work", reg: "phrase", topic: "هندسة", ex: "أي طلب برى نطاق العمل، يبي له عقد ملحق." },
      { id: "eg05", ar: "تضخّم النطاق", tr: "taḍakhkhum in-niṭāq", en: "scope creep", reg: "phrase", topic: "هندسة", ex: "المشروع تأخر شهرين بسبب تضخّم النطاق، مو بسبب الفريق." },
      { id: "eg06", ar: "الجدول الزمني", tr: "il-jadwal iz-zamani", en: "timeline, schedule", reg: "msa", topic: "هندسة", ex: "الجدول الزمني متفائل وايد — ماكو فيه هامش لأي مشكلة." },
      { id: "eg07", ar: "المسار الحرج", tr: "il-masār il-ḥarij", en: "critical path", reg: "phrase", topic: "هندسة", ex: "أي تأخير على المسار الحرج يأخر المشروع كله." },
      { id: "eg08", ar: "التسليم", tr: "it-taslīm", en: "handover, delivery", reg: "msa", topic: "هندسة", ex: "التسليم مو نهاية الشغل — بعده الضمان والصيانة." },
      { id: "eg09", ar: "ضبط الجودة", tr: "ḍabṭ il-jōda", en: "quality control", reg: "phrase", topic: "هندسة", ex: "ضبط الجودة يكشف العيب قبل لا يوصل العميل." },
      { id: "eg10", ar: "التفاوت المسموح", tr: "it-tafāwut il-masmūḥ", en: "tolerance", reg: "phrase", topic: "هندسة", ex: "القطعة برى التفاوت المسموح، لازم ترجع للتصنيع." },
      { id: "eg11", ar: "الإجهاد", tr: "il-ijhād", en: "stress (material)", reg: "msa", topic: "هندسة", ex: "الإجهاد المتكرر يكسر المعدن حتى لو ما تجاوز الحد." },
      { id: "eg12", ar: "الحمل", tr: "il-ḥiml", en: "load", reg: "msa", topic: "هندسة", ex: "لازم نحسب الحمل الأقصى، مو المتوسط." },
      { id: "eg13", ar: "عامل الأمان", tr: "ʿāmil il-amān", en: "safety factor", reg: "phrase", topic: "هندسة", ex: "عامل الأمان يعني نصممها تتحمل أكثر من اللي نتوقعه." },
      { id: "eg14", ar: "المتانة", tr: "il-matāna", en: "durability", reg: "msa", topic: "هندسة", ex: "متانة أعلى تعني تكلفة أول أكبر وصيانة أقل." },
      { id: "eg15", ar: "الصيانة الوقائية", tr: "iṣ-ṣiyāna il-wiqāʾiyya", en: "preventive maintenance", reg: "phrase", topic: "هندسة", ex: "الصيانة الوقائية أرخص من العطل بعشر مرات." },
      { id: "eg16", ar: "التوقف عن العمل", tr: "it-tawaqquf ʿan il-ʿamal", en: "downtime", reg: "phrase", topic: "هندسة", ex: "كل ساعة توقف عن العمل تكلفنا أكثر من الإصلاح نفسه." },
      { id: "eg17", ar: "المعايرة", tr: "il-muʿāyara", en: "calibration", reg: "msa", topic: "هندسة", ex: "الجهاز بدون معايرة دورية يعطيك أرقام تثق فيها وهي غلط." },
      { id: "eg18", ar: "الأتمتة", tr: "il-atmata", en: "automation", reg: "msa", topic: "هندسة", ex: "الأتمتة ما تلغي الناس — تنقلهم لشغل أذكى." },
      { id: "eg19", ar: "الاستشعار", tr: "il-istishʿār", en: "sensing, sensors", reg: "msa", topic: "هندسة", ex: "أنظمة الاستشعار تنبهك قبل لا يصير العطل." },
      { id: "eg20", ar: "السعة", tr: "is-saʿa", en: "capacity", reg: "msa", topic: "هندسة", ex: "المحطة تشتغل على كامل السعة، فماكو مجال لأي زيادة." },
      { id: "eg21", ar: "البنية التحتية", tr: "il-binya it-taḥtiyya", en: "infrastructure", reg: "msa", topic: "هندسة", ex: "البنية التحتية مو مشاريع تنقص — هي أساس كل شي فوقها." },
      { id: "eg22", ar: "الأساسات", tr: "il-asāsāt", en: "foundations", reg: "msa", topic: "هندسة", ex: "غلطة بالأساسات ما تنصلح بأي تشطيب." },
      { id: "eg23", ar: "الخرسانة المسلحة", tr: "il-kharasāna il-musallaḥa", en: "reinforced concrete", reg: "msa", topic: "هندسة", ex: "الخرسانة المسلحة تتحمل الضغط والشد مع بعض." },
      { id: "eg24", ar: "المخطط التنفيذي", tr: "il-mukhaṭṭaṭ it-tanfīdhi", en: "execution drawing", reg: "phrase", topic: "هندسة", ex: "لا يبدأ أحد شغل قبل ما يعتمد المخطط التنفيذي." },
      { id: "eg25", ar: "المناقصة", tr: "il-munāqaṣa", en: "tender, bid", reg: "msa", topic: "هندسة", ex: "المناقصة راحت لأرخص سعر — ودفعنا الفرق بالجودة." },
      { id: "eg26", ar: "المقاول", tr: "il-muqāwil", en: "contractor", reg: "msa", topic: "هندسة", ex: "اختيار المقاول أهم من اختيار التصميم أحيان." },
      { id: "eg27", ar: "التكلفة الإجمالية للملكية", tr: "it-taklifa il-ijmāliyya lil-milkiyya", en: "total cost of ownership", reg: "phrase", topic: "هندسة", ex: "لا تحسب سعر الشراء بس — احسب التكلفة الإجمالية للملكية." },
      { id: "eg28", ar: "قابلية التوسّع", tr: "qābiliyyat it-tawassuʿ", en: "scalability", reg: "phrase", topic: "هندسة", ex: "النظام يشتغل زين الحين، بس ماكو فيه قابلية توسّع." },
    ],
  },
];
