/*
 * SEED_PACKS — curated expansion packs. Words are NOT active until the pack
 * is added from the الحزم screen, so the deck grows when Bader chooses,
 * never by surprise. Same card shape as SEED_MANUAL.
 */
const SEED_PACKS = [
  {
    key: "connectors",
    name: "روابط النقاش",
    desc: "أدوات الربط اللي ترفع مستوى كلامك بالمجالس الجادة — من «بس» و«يعني» إلى لغة المحاور المتمكن.",
    words: [
      { id: "p101", ar: "بالتالي", tr: "bit-tāli", en: "therefore, consequently", reg: "msa", topic: "نقاش", ex: "الميزانية محدودة، وبالتالي لازم نرتب الأولويات." },
      { id: "p102", ar: "علاوة على ذلك", tr: "ʿilāwatan ʿala dhālik", en: "moreover", reg: "phrase", topic: "نقاش", ex: "المشروع مكلف، وعلاوة على ذلك السوق مو جاهز له." },
      { id: "p103", ar: "بغض النظر عن", tr: "bi-ghaḍḍ in-naẓar ʿan", en: "regardless of", reg: "phrase", topic: "نقاش", ex: "بغض النظر عن النتيجة، التجربة نفسها مكسب." },
      { id: "p104", ar: "من جهة... ومن جهة أخرى", tr: "min jiha... u-min jiha ukhra", en: "on one hand... on the other", reg: "phrase", topic: "نقاش", ex: "من جهة التكلفة أقل، ومن جهة أخرى الجودة أضعف." },
      { id: "p105", ar: "من منطلق", tr: "min munṭalaq", en: "from the standpoint of", reg: "phrase", topic: "نقاش", ex: "أتكلم من منطلق تجربة، مو من منطلق نظرية." },
      { id: "p106", ar: "بناءً على", tr: "bināʾan ʿala", en: "based on", reg: "phrase", topic: "نقاش", ex: "بناءً على الأرقام اللي قدامنا، القرار واضح." },
      { id: "p107", ar: "في نهاية المطاف", tr: "fi nihāyat il-maṭāf", en: "at the end of the day", reg: "phrase", topic: "نقاش", ex: "في نهاية المطاف، السوق هو اللي يحكم." },
      { id: "p108", ar: "لا سيما", tr: "lā siyyama", en: "especially, particularly", reg: "msa", topic: "نقاش", ex: "القراءة تفيد الكل، لا سيما اللي يكتبون." },
      { id: "p109", ar: "بمعنى آخر", tr: "bi-maʿna ākhar", en: "in other words", reg: "phrase", topic: "نقاش", ex: "بمعنى آخر: اللي ما يتطور، يتأخر." },
      { id: "p110", ar: "على أرض الواقع", tr: "ʿala arḍ il-wāqiʿ", en: "on the ground, in reality", reg: "phrase", topic: "نقاش", ex: "الخطة حلوة على الورق، بس على أرض الواقع أكو تحديات." },
      { id: "p111", ar: "جوهر الموضوع", tr: "jawhar il-mawḍūʿ", en: "the essence of the matter", reg: "phrase", topic: "نقاش", ex: "خلنا نرجع لجوهر الموضوع ولا نتشتت بالفروع." },
      { id: "p112", ar: "أتفق معك في... وأختلف في...", tr: "attafiq maʿāk fi...", en: "I agree on X, differ on Y (polite disagreement)", reg: "phrase", topic: "نقاش", ex: "أتفق وياك بالتشخيص، وأختلف وياك بالحل.", note: "أرقى صيغة اعتراض — تثبت إنك سامع قبل ما ترد" },
      { id: "p113", ar: "لا نستبق الأحداث", tr: "lā nastabiq il-aḥdāth", en: "let's not get ahead of ourselves", reg: "phrase", topic: "نقاش", ex: "لا نستبق الأحداث — خل نشوف نتائج أول شهر." },
      { id: "p114", ar: "إن صح التعبير", tr: "in ṣaḥḥ it-taʿbīr", en: "if the expression fits, so to speak", reg: "phrase", topic: "نقاش", ex: "هذا انتحار تجاري، إن صح التعبير." },
      { id: "p115", ar: "يترتب على", tr: "yatarattab ʿala", en: "results from, follows from", reg: "msa", topic: "نقاش", ex: "لازم نفهم شنو يترتب على القرار قبل لا نمضيه." },
      { id: "p116", ar: "حجر الأساس", tr: "ḥajar il-asās", en: "the cornerstone", reg: "phrase", topic: "نقاش", ex: "الثقة حجر الأساس بأي شراكة." },
    ],
  },
  {
    key: "social",
    name: "مجاملات ومناسبات كويتية",
    desc: "العبارات اللي تخليك حاضر البديهة بكل موقف اجتماعي — تحية، شكر، تهنئة، وردودها الصحيحة.",
    words: [
      { id: "p201", ar: "عساكم من عواده", tr: "ʿasākum min ʿuwwāda", en: "Eid greeting: may you live to see it return", reg: "kw", topic: "مجاملات", ex: "تنقال بالعيد: «عساكم من عواده» — والرد: «وأنتم من عايدينه» أو «أيامكم سعيدة»." },
      { id: "p202", ar: "ما قصرت", tr: "mā gaṣṣart", en: "you did great / thank you (lit. you fell not short)", reg: "kw", topic: "مجاملات", ex: "«خلصت لك المعاملة» — «ما قصرت والله!» والرد: «هذا واجبي»." },
      { id: "p203", ar: "تدلل", tr: "tdallal", en: "at your service, by all means", reg: "kw", topic: "مجاملات", ex: "«تقدر توصلني المطار؟» — «تدلل، خمس دقايق وأنا عندك»." },
      { id: "p204", ar: "عسى ما شر", tr: "ʿasa mā sharr", en: "I hope nothing's wrong?", reg: "kw", topic: "مجاملات", ex: "«شفت اتصالاتك — عسى ما شر؟» والرد: «شر ما ييك، كله خير»." },
      { id: "p205", ar: "تستاهل", tr: "tistāhil", en: "you deserve it", reg: "kw", topic: "مجاملات", ex: "مبروك الترقية — تستاهل كل خير!" },
      { id: "p206", ar: "عقبالك", tr: "ʿugbālik", en: "may you be next (returning a congratulation)", reg: "kw", topic: "مجاملات", ex: "«مبروك التخرج» — «الله يبارك فيك، عقبالك!»" },
      { id: "p207", ar: "حياك الله", tr: "ḥayyāk aḷḷa", en: "welcome (lit. may God greet you)", reg: "kw", topic: "مجاملات", ex: "«حياك الله، البيت بيتك» — والرد: «الله يحييك»." },
      { id: "p208", ar: "يعطيك العافية", tr: "yaʿṭīk il-ʿāfya", en: "thanks for your effort (lit. may God give you health)", reg: "kw", topic: "مجاملات", ex: "«يعطيك العافية عالشغل اليوم» — والرد: «الله يعافيك»." },
      { id: "p209", ar: "من طرفك", tr: "min ṭarfik", en: "thanks to you, through your help", reg: "kw", topic: "مجاملات", ex: "من طرفك مشت الأمور كلها — ما ننسى لك هالطيب." },
      { id: "p210", ar: "قدها وقدود", tr: "gadha u-gudūd", en: "fully capable, more than up to it", reg: "kw", topic: "مجاملات", ex: "لا تشيل هم المشروع — هي قدها وقدود." },
      { id: "p211", ar: "طال عمرك", tr: "ṭāl ʿumrik", en: "respectful address (lit. may your life be long)", reg: "kw", topic: "مجاملات", ex: "شرايك طال عمرك نأجلها لباچر؟" },
      { id: "p212", ar: "أبشر", tr: "abshir", en: "consider it done", reg: "kw", topic: "مجاملات", ex: "«محتاجين التقرير اليوم» — «أبشر، يوصلك قبل المغرب»." },
      { id: "p213", ar: "على راسي", tr: "ʿala rāsi", en: "with pleasure and honor", reg: "kw", topic: "مجاملات", ex: "طلبك على راسي — تم." },
      { id: "p214", ar: "خوش", tr: "khōsh", en: "good, fine (before a noun)", reg: "kw", topic: "يومي", ex: "خوش فكرة! منو يتبناها؟", note: "خوش كلام، خوش ريال، خوش شغل — تسبق الاسم دايمًا" },
      { id: "p215", ar: "يا هلا والله", tr: "yā hala waḷḷa", en: "warm welcome greeting", reg: "kw", topic: "مجاملات", ex: "يا هلا والله! زمان عنك — وينك مختفي؟" },
      { id: "p216", ar: "استانست", tr: "istānast", en: "I had a great time, I was delighted", reg: "kw", topic: "مجاملات", ex: "استانست بشوفتك اليوم — لا تقطعنا.", note: "من الونسة — كلمة كويتية دافئة للفرح بالصحبة" },
      { id: "p217", ar: "لا هنت", tr: "lā hint", en: "thank you (lit. may you not be belittled)", reg: "kw", topic: "مجاملات", ex: "«وصلتك الأوراق» — «لا هنت»." },
      { id: "p218", ar: "بالعافية", tr: "bil-ʿāfya", en: "bon appétit", reg: "kw", topic: "مجاملات", ex: "تنقال للي ياكل: «بالعافية» — والرد: «الله يعافيك»." },
    ],
  },
  {
    key: "proverbs",
    name: "أمثال متداولة بالكويت",
    desc: "أمثال حية بالمجالس الكويتية والخليجية — المثل بمكانه الصح يختصر خطبة كاملة. أفضل مصدر للتأكد: كبار العائلة.",
    words: [
      { id: "p301", ar: "اللي ما يعرف الصقر يشويه", tr: "illi mā yaʿrif iṣ-ṣagir yishwīh", en: "who doesn't know the falcon's worth grills it", reg: "kw", topic: "أمثال", ex: "عرضوا فكرته ورفضوها — قلت له: اللي ما يعرف الصقر يشويه.", note: "يُضرب لمن يستهين بشي ثمين جهلًا بقيمته" },
      { id: "p302", ar: "الطول طول نخلة والعقل عقل صخلة", tr: "iṭ-ṭūl ṭūl nakhla wil-ʿagil ʿagil ṣakhla", en: "tall as a palm, mind of a goat kid", reg: "kw", topic: "أمثال", ex: "شكله يهيّب بس تصرفاته…‏ الطول طول نخلة والعقل عقل صخلة.", note: "للمظهر بلا عقل — تنقال مزحًا بين الربع" },
      { id: "p303", ar: "من طلع من داره قل مقداره", tr: "min ṭalaʿ min dāra gall migdāra", en: "who leaves his home loses his standing", reg: "kw", topic: "أمثال", ex: "بديرتك لك وزنك وناسك — من طلع من داره قل مقداره." },
      { id: "p304", ar: "يا ما تحت السواهي دواهي", tr: "yā mā taḥt is-sawāhi dawāhi", en: "beneath the quiet ones lie cunning depths", reg: "kw", topic: "أمثال", ex: "لا يغرك هدوءه — يا ما تحت السواهي دواهي." },
      { id: "p305", ar: "اللي ما له أول ما له تالي", tr: "illi mā la awwal mā la tāli", en: "what has no beginning has no end", reg: "kw", topic: "أمثال", ex: "أساس المشروع لازم يكون صح — اللي ما له أول ما له تالي." },
      { id: "p306", ar: "الجود من الموجود", tr: "il-jūd min il-mawjūd", en: "generosity is from what one has", reg: "kw", topic: "أمثال", ex: "ما عندنا إلا هذا، والجود من الموجود." },
      { id: "p307", ar: "اللي يبي الدح ما يقول أح", tr: "illi yabi id-daḥḥ mā ygūl aḥḥ", en: "who wants the prize doesn't cry ouch", reg: "kw", topic: "أمثال", ex: "تبي النتيجة؟ اصبر على التعب — اللي يبي الدح ما يقول أح." },
      { id: "p308", ar: "كل تأخيرة فيها خيرة", tr: "kill taʾkhīra fīha khīra", en: "every delay carries a blessing", reg: "kw", topic: "أمثال", ex: "طارت عليك الفرصة؟ كل تأخيرة فيها خيرة." },
      { id: "p309", ar: "ضربتين بالراس توجع", tr: "ḍarbitēn bir-rās tōjaʿ", en: "two blows to the head hurt (don't repeat a mistake)", reg: "kw", topic: "أمثال", ex: "جربناها قبل وخسرنا — ضربتين بالراس توجع." },
      { id: "p310", ar: "اللي استحوا ماتوا", tr: "illi istaḥaw mātaw", en: "the overly shy perished (speak up)", reg: "kw", topic: "أمثال", ex: "اسأل ولا تحاتي — اللي استحوا ماتوا." },
    ],
  },
  {
    key: "corrections",
    name: "مصطلحات مصححة (إنتاج وفضاء واقتصاد)",
    desc: "المصطلحات الصحيحة لمجالاتك — بدال الترجمات المختلقة اللي كانت بقوائم الذكاء الاصطناعي القديمة.",
    words: [
      { id: "p401", ar: "الزبدة", tr: "iz-zibda", en: "the bottom line, the gist", reg: "kw", topic: "نقاش", ex: "طولنا بالشرح — الزبدة: المشروع مربح والتوقيت مناسب." },
      { id: "p402", ar: "مؤثرات خاصة", tr: "muʾaththirāt khāṣṣa", en: "special effects / VFX", reg: "msa", topic: "إنتاج", ex: "شغلنا بالإنتاج أغلبه مؤثرات خاصة وتصحيح ألوان.", note: "التصحيح: مو «معجزات» مثل ما قالت القائمة القديمة" },
      { id: "p403", ar: "تصحيح الألوان", tr: "taṣḥīḥ il-alwān", en: "color grading", reg: "msa", topic: "إنتاج", ex: "اللقطة تتغير شخصيتها كليًا عقب تصحيح الألوان." },
      { id: "p404", ar: "مونتاج", tr: "montāj", en: "editing (film)", reg: "msa", topic: "إنتاج", ex: "الفيلم ينولد مرتين: مرة بالتصوير ومرة بالمونتاج." },
      { id: "p405", ar: "زاوية الكاميرا", tr: "zāwiyat il-kāmera", en: "camera angle", reg: "msa", topic: "إنتاج", ex: "غيرنا زاوية الكاميرا وتغير إحساس المشهد كله." },
      { id: "p406", ar: "تصوير بطيء", tr: "taṣwīr baṭīʾ", en: "slow motion", reg: "msa", topic: "إنتاج", ex: "لقطة النهاية بالتصوير البطيء عطت المشهد رهبة." },
      { id: "p407", ar: "الجاذبية", tr: "il-jādhibiyya", en: "gravity", reg: "msa", topic: "علوم", ex: "بدون الجاذبية، أبسط حركة تصير تحدي — اسأل رواد الفضاء.", note: "التصحيح: الجاذبية (القائمة القديمة قالت «قدم» — والقدم هي الرجل!)" },
      { id: "p408", ar: "الزمكان", tr: "iz-zamakān", en: "spacetime", reg: "msa", topic: "علوم", ex: "الكتلة الكبيرة تحني الزمكان — هذا جوهر النسبية العامة." },
      { id: "p409", ar: "مجرة / مجرات", tr: "majarra / majarrāt", en: "galaxy / galaxies", reg: "msa", topic: "علوم", ex: "درب التبانة مجرتنا، وجيرانها ملايين المجرات." },
      { id: "p410", ar: "مركبة فضائية", tr: "markaba faḍāʾiyya", en: "spacecraft", reg: "msa", topic: "علوم", ex: "حلم أي رائد فضاء: مقعد على متن مركبة فضائية." },
      { id: "p411", ar: "رائد فضاء", tr: "rāʾid faḍāʾ", en: "astronaut", reg: "msa", topic: "علوم", ex: "ليش لا يكون أول رائد فضاء كويتي من هالجيل؟" },
      { id: "p412", ar: "ضرائب", tr: "ḍarāʾib", en: "taxes", reg: "msa", topic: "اقتصاد", ex: "النقاش عن الضرائب بالخليج كله حساسية.", note: "التصحيح: ضرائب (مو «خراج» — هذاك مصطلح تاريخي قديم)" },
      { id: "p413", ar: "استقطاب المواهب", tr: "istiqṭāb il-mawāhib", en: "talent recruitment", reg: "msa", topic: "شغل", ex: "الشركات الكبيرة تتنافس على استقطاب المواهب قبل التخرج.", note: "التصحيح: مو «تشجير» — التشجير هو زراعة الأشجار!" },
      { id: "p414", ar: "رأي عام", tr: "raʾy ʿāmm", en: "public opinion", reg: "msa", topic: "سياسة", ex: "الرأي العام قوة — واللي يفهمه يسبق غيره." },
      { id: "p415", ar: "مفاوضات", tr: "mufāwaḍāt", en: "negotiations", reg: "msa", topic: "سياسة", ex: "المفاوضات الناجحة يطلع منها الطرفين كسبانين." },
      { id: "p416", ar: "حقيبة وزارية", tr: "ḥaqība wizāriyya", en: "ministerial portfolio", reg: "msa", topic: "سياسة", ex: "أهم سؤال عقب التشكيل: منو أخذ الحقيبة الوزارية الفلانية؟" },
    ],
  },
];
